"""add is_active and is_deleted columns to notification table

Revision ID: 01241d207496
Revises: 5a630ac4adce
Create Date: 2026-06-25 15:12:59.992033

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "01241d207496"
down_revision: Union[str, Sequence[str], None] = "5a630ac4adce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("notification", sa.Column("is_active", sa.Boolean(), nullable=True))
    op.add_column("notification", sa.Column("is_deleted", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("notification", "is_deleted")
    op.drop_column("notification", "is_active")
    # ### end Alembic commands ###
