"""added stock quantity to product table, and store reply count to review table

Revision ID: 01ef0d7b0fe8
Revises: c08ac8abdea7
Create Date: 2026-03-16 15:16:45.836755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01ef0d7b0fe8'
down_revision: Union[str, Sequence[str], None] = 'c08ac8abdea7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('stock_quantity', sa.Integer(), nullable=True))
    op.add_column('reviews', sa.Column('product_reply_count', sa.Integer(), nullable=False))
    op.add_column('reviews', sa.Column('store_reply_count', sa.Integer(), nullable=False))
    op.drop_column('reviews', 'reply_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('reply_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('reviews', 'store_reply_count')
    op.drop_column('reviews', 'product_reply_count')
    op.drop_column('products', 'stock_quantity')
    # ### end Alembic commands ###
