"""add ban columns

Revision ID: 039add157915
Revises: 53da0f54f18e
Create Date: 2026-07-29 16:07:08.700860

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "039add157915"
down_revision: Union[str, Sequence[str], None] = "53da0f54f18e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    from sqlalchemy.dialects import postgresql

    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    ban_enum = postgresql.ENUM("days", "months", name="banunit")
    ban_enum.create(op.get_bind(), checkfirst=True)
    op.add_column("user", sa.Column("indefinite_ban", sa.Boolean(), nullable=True))
    op.add_column(
        "user",
        sa.Column("deactivation_time", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "user", sa.Column("ban_date", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "user",
        sa.Column(
            "ban_unit",
            sa.Enum("days", "months", name="banunit"),
            nullable=True,
        ),
    )
    op.add_column("user", sa.Column("ban_reaon", sa.String(), nullable=True))
    op.add_column("user", sa.Column("ban_count", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=False)
    op.create_index(
        op.f("ix_user_indefinite_ban"), "user", ["indefinite_ban"], unique=False
    )
    op.create_index(op.f("ix_user_is_active"), "user", ["is_active"], unique=False)
    op.create_index(op.f("ix_user_is_banned"), "user", ["is_banned"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_is_banned"), table_name="user")
    op.drop_index(op.f("ix_user_is_active"), table_name="user")
    op.drop_index(op.f("ix_user_indefinite_ban"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_column("user", "ban_count")
    op.drop_column("user", "ban_reaon")
    op.drop_column("user", "ban_unit")
    op.drop_column("user", "ban_period")
    op.drop_column("user", "ban_date")
    op.drop_column("user", "deactivation_time")
    op.drop_column("user", "indefinite_ban")
    op.drop_column("user", "is_banned")
    # ### end Alembic commands ###
