"""add MembershipType enum

Revision ID: 03fcd6b727fe
Revises: 126151d4397f
Create Date: 2026-06-09 17:05:51.357628

"""

from typing import Sequence, Union
from sqlalchemy.dialects import postgresql
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "03fcd6b727fe"
down_revision: Union[str, Sequence[str], None] = "126151d4397f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    membership_enum = postgresql.ENUM(
        "Standard", "Regular", "Premium", name="membershiptype"
    )
    membership_enum.create(op.get_bind(), checkfirst=True)
    op.alter_column("membership", "user_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "membership", "store_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "membership",
        "membership_type",
        existing_type=sa.VARCHAR(),
        type_=sa.Enum("Standard", "Regular", "Premium", name="membershiptype"),
        postgresql_using="membership_type::membershiptype",
        nullable=False,
    )
    op.alter_column(
        "membership", "is_active", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column(
        "membership", "is_deleted", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column(
        "membership", "is_pause", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column(
        "membership",
        "pause_date",
        existing_type=sa.DATE(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "membership",
        "delete_date",
        existing_type=sa.DATE(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "membership",
        "reactivation_date",
        existing_type=sa.DATE(),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "membership",
        "start_date",
        existing_type=sa.DATE(),
        type_=sa.DateTime(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "membership",
        "start_date",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.DATE(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "membership",
        "reactivation_date",
        existing_type=sa.DateTime(),
        type_=sa.DATE(),
        existing_nullable=True,
    )
    op.alter_column(
        "membership",
        "delete_date",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.DATE(),
        existing_nullable=True,
    )
    op.alter_column(
        "membership",
        "pause_date",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.DATE(),
        existing_nullable=True,
    )
    op.alter_column("membership", "is_pause", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column(
        "membership", "is_deleted", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "membership", "is_active", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "membership",
        "membership_type",
        existing_type=sa.Enum("Standard", "Regular", "Premium", name="membershiptype"),
        type_=sa.VARCHAR(),
        nullable=True,
    )
    op.alter_column("membership", "store_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("membership", "user_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
