"""delete ProductImage table

Revision ID: 04f9df2766e9
Revises: 1c8fbf255f5b
Create Date: 2026-09-02 17:13:40.685658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04f9df2766e9'
down_revision: Union[str, Sequence[str], None] = '1c8fbf255f5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_image_product_id'), table_name='product_image')
    op.drop_index(op.f('ix_product_image_store_id'), table_name='product_image')
    op.drop_table('product_image')
    op.alter_column('user', 'date_of_birth',
               existing_type=sa.DATE(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'date_of_birth',
               existing_type=sa.DATE(),
               server_default=sa.text("'2000-09-14'::date"),
               existing_nullable=False)
    op.create_table('product_image',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('product_image_product_id_fkey')),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], name=op.f('product_image_store_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('product_image_pkey'))
    )
    op.create_index(op.f('ix_product_image_store_id'), 'product_image', ['store_id'], unique=False)
    op.create_index(op.f('ix_product_image_product_id'), 'product_image', ['product_id'], unique=False)
    # ### end Alembic commands ###
