"""add avg_rating column to store table

Revision ID: 073fe2ae36ee
Revises: 61f2e58a30fa
Create Date: 2026-05-07 17:07:12.802117

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "073fe2ae36ee"
down_revision: Union[str, Sequence[str], None] = "61f2e58a30fa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stores", "review_count")
    op.drop_column("stores", "avg_rating")
    op.drop_column("products", "review_count")
    op.drop_column("products", "avg_rating")
    # ### end Alembic commands ###
