"""add date_of_birth column to user table

Revision ID: 0d47ce9bb3c1
Revises: b1c3ab7378fa
Create Date: 2026-08-07 12:21:44.611220

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM as PG_ENUM

# revision identifiers, used by Alembic.
revision: str = "0d47ce9bb3c1"
down_revision: Union[str, Sequence[str], None] = "b1c3ab7378fa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    role_enum = PG_ENUM("Owner", "Admin", "user", "customer_care", name="roleenum")
    role_enum.create(op.get_bind(), checkfirst=True)
    op.drop_index(op.f("ix_cart_id"), table_name="cart")
    op.drop_index(op.f("ix_cartitem_id"), table_name="cartitem")
    op.drop_index(op.f("ix_category_id"), table_name="category")
    op.drop_index(op.f("ix_category_name"), table_name="category")
    op.create_unique_constraint(None, "category", ["name"])
    op.drop_index(op.f("ix_inventory_id"), table_name="inventory")
    op.drop_index(op.f("ix_membership_id"), table_name="membership")
    op.drop_index(op.f("ix_message_id"), table_name="message")
    op.drop_index(op.f("ix_notification_id"), table_name="notification")
    op.drop_index(op.f("ix_order_id"), table_name="order")
    op.drop_index(op.f("ix_order_reference_id"), table_name="order")
    op.create_unique_constraint(None, "order", ["reference_id"])
    op.drop_index(op.f("ix_orderitem_id"), table_name="orderitem")
    op.drop_index(op.f("ix_payment_checkout_url"), table_name="payment")
    op.drop_index(op.f("ix_payment_id"), table_name="payment")
    op.drop_index(op.f("ix_payment_reference_id"), table_name="payment")
    op.create_unique_constraint(None, "payment", ["reference_id"])
    op.create_unique_constraint(None, "payment", ["checkout_url"])
    op.drop_index(op.f("ix_product_id"), table_name="product")
    op.drop_index(op.f("ix_product_image_id"), table_name="product_image")
    op.drop_index(op.f("ix_react_id"), table_name="react")
    op.drop_index(op.f("ix_refund_id"), table_name="refund")
    op.drop_index(op.f("ix_refund_refund_id"), table_name="refund")
    op.create_unique_constraint(None, "refund", ["refund_id"])
    op.drop_index(op.f("ix_reply_id"), table_name="reply")
    op.drop_index(op.f("ix_review_id"), table_name="review")
    op.alter_column("store", "store_name", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_index(op.f("ix_store_id"), table_name="store")
    op.drop_index(op.f("ix_store_slug"), table_name="store")
    op.drop_index(op.f("ix_store_store_name"), table_name="store")
    op.create_unique_constraint(None, "store", ["slug"])
    op.create_unique_constraint(None, "store", ["store_name"])
    op.drop_index(op.f("ix_store_account_id"), table_name="store_account")
    op.drop_index(op.f("ix_store_owners_stores_id"), table_name="store_owners")
    op.drop_index(op.f("ix_store_owners_users_id"), table_name="store_owners")
    op.drop_index(op.f("ix_store_staffs_stores_id"), table_name="store_staffs")
    op.drop_index(op.f("ix_store_staffs_users_id"), table_name="store_staffs")
    op.drop_index(op.f("ix_subcategory_id"), table_name="subcategory")
    op.drop_index(op.f("ix_subcategory_name"), table_name="subcategory")
    op.create_unique_constraint(None, "subcategory", ["name"])
    op.drop_index(op.f("ix_subscription_id"), table_name="subscription")
    op.drop_index(op.f("ix_ticket_id"), table_name="ticket")
    op.add_column(
        "user",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.alter_column(
        "user",
        "date_of_birth",
        existing_type=sa.DATE(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "user",
        "role",
        existing_type=sa.VARCHAR(),
        type_=role_enum,
        postgresql_using="role::roleenum",
        existing_nullable=False,
    )
    op.alter_column(
        "user", "indefinite_ban", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_index(op.f("ix_user_first_name"), table_name="user")
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.drop_index(op.f("ix_user_indefinite_ban"), table_name="user")
    op.drop_index(op.f("ix_user_is_active"), table_name="user")
    op.drop_index(op.f("ix_user_is_banned"), table_name="user")
    op.drop_index(op.f("ix_user_role"), table_name="user")
    op.drop_index(op.f("ix_user_surname"), table_name="user")
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.create_index(
        "idx_banned_users",
        "user",
        ["id"],
        unique=False,
        postgresql_where=sa.text("is_banned = True"),
    )
    op.create_index(
        "idx_deactivated_users",
        "user",
        ["id"],
        unique=False,
        postgresql_where=sa.text("is_active = False"),
    )
    op.create_index(
        "idx_indefinite_ban",
        "user",
        ["id"],
        unique=False,
        postgresql_where=sa.text("indefinite_ban = True"),
    )
    op.create_unique_constraint(None, "user", ["username"])
    op.create_unique_constraint(None, "user", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")
    op.drop_constraint(None, "user", type_="unique")
    op.drop_index(
        "idx_indefinite_ban",
        table_name="user",
        postgresql_where=sa.text("indefinite_ban = True"),
    )
    op.drop_index(
        "idx_deactivated_users",
        table_name="user",
        postgresql_where=sa.text("is_active = False"),
    )
    op.drop_index(
        "idx_banned_users",
        table_name="user",
        postgresql_where=sa.text("is_banned = True"),
    )
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)
    op.create_index(op.f("ix_user_surname"), "user", ["surname"], unique=False)
    op.create_index(op.f("ix_user_role"), "user", ["role"], unique=False)
    op.create_index(op.f("ix_user_is_banned"), "user", ["is_banned"], unique=False)
    op.create_index(op.f("ix_user_is_active"), "user", ["is_active"], unique=False)
    op.create_index(
        op.f("ix_user_indefinite_ban"), "user", ["indefinite_ban"], unique=False
    )
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)
    op.create_index(op.f("ix_user_first_name"), "user", ["first_name"], unique=False)
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=False)
    op.alter_column("user", "indefinite_ban", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column(
        "user",
        "role",
        existing_type=sa.Enum(
            "Owner", "Admin", "user", "customer_care", name="roleenum"
        ),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.drop_column("user", "updated_at")
    op.drop_column("user", "created_at")
    op.create_index(op.f("ix_ticket_id"), "ticket", ["id"], unique=False)
    op.create_index(op.f("ix_subscription_id"), "subscription", ["id"], unique=False)
    op.drop_constraint(None, "subcategory", type_="unique")
    op.create_index(op.f("ix_subcategory_name"), "subcategory", ["name"], unique=True)
    op.create_index(op.f("ix_subcategory_id"), "subcategory", ["id"], unique=False)
    op.create_index(
        op.f("ix_store_staffs_users_id"), "store_staffs", ["users_id"], unique=False
    )
    op.create_index(
        op.f("ix_store_staffs_stores_id"), "store_staffs", ["stores_id"], unique=False
    )
    op.create_index(
        op.f("ix_store_owners_users_id"), "store_owners", ["users_id"], unique=False
    )
    op.create_index(
        op.f("ix_store_owners_stores_id"), "store_owners", ["stores_id"], unique=False
    )
    op.create_index(op.f("ix_store_account_id"), "store_account", ["id"], unique=False)
    op.drop_constraint(None, "store", type_="unique")
    op.drop_constraint(None, "store", type_="unique")
    op.create_index(op.f("ix_store_store_name"), "store", ["store_name"], unique=True)
    op.create_index(op.f("ix_store_slug"), "store", ["slug"], unique=True)
    op.create_index(op.f("ix_store_id"), "store", ["id"], unique=False)
    op.alter_column("store", "store_name", existing_type=sa.VARCHAR(), nullable=False)
    op.create_index(op.f("ix_review_id"), "review", ["id"], unique=False)
    op.create_index(op.f("ix_reply_id"), "reply", ["id"], unique=False)
    op.drop_constraint(None, "refund", type_="unique")
    op.create_index(op.f("ix_refund_refund_id"), "refund", ["refund_id"], unique=True)
    op.create_index(op.f("ix_refund_id"), "refund", ["id"], unique=False)
    op.create_index(op.f("ix_react_id"), "react", ["id"], unique=False)
    op.create_index(op.f("ix_product_image_id"), "product_image", ["id"], unique=False)
    op.create_index(op.f("ix_product_id"), "product", ["id"], unique=False)
    op.drop_constraint(None, "payment", type_="unique")
    op.drop_constraint(None, "payment", type_="unique")
    op.create_index(
        op.f("ix_payment_reference_id"), "payment", ["reference_id"], unique=True
    )
    op.create_index(op.f("ix_payment_id"), "payment", ["id"], unique=False)
    op.create_index(
        op.f("ix_payment_checkout_url"), "payment", ["checkout_url"], unique=True
    )
    op.create_index(op.f("ix_orderitem_id"), "orderitem", ["id"], unique=False)
    op.drop_constraint(None, "order", type_="unique")
    op.create_index(
        op.f("ix_order_reference_id"), "order", ["reference_id"], unique=True
    )
    op.create_index(op.f("ix_order_id"), "order", ["id"], unique=False)
    op.create_index(op.f("ix_notification_id"), "notification", ["id"], unique=False)
    op.create_index(op.f("ix_message_id"), "message", ["id"], unique=False)
    op.create_index(op.f("ix_membership_id"), "membership", ["id"], unique=False)
    op.create_index(op.f("ix_inventory_id"), "inventory", ["id"], unique=False)
    op.drop_constraint(None, "category", type_="unique")
    op.create_index(op.f("ix_category_name"), "category", ["name"], unique=True)
    op.create_index(op.f("ix_category_id"), "category", ["id"], unique=False)
    op.create_index(op.f("ix_cartitem_id"), "cartitem", ["id"], unique=False)
    op.create_index(op.f("ix_cart_id"), "cart", ["id"], unique=False)
    # ### end Alembic commands ###
