"""add nullable True for price id and plan price columns

Revision ID: 0e4175cba294
Revises: 73528a5c9089
Create Date: 2026-04-13 16:52:49.073809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e4175cba294'
down_revision: Union[str, Sequence[str], None] = '73528a5c9089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'price_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('subscriptions', 'plan_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'plan_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('subscriptions', 'price_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
