"""add verification_status, verified_at and rejected_reasoncolumns in StoreAccount table

Revision ID: 0f2186d10fea
Revises: 2ce3a9eda463
Create Date: 2026-05-14 15:48:11.580693

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0f2186d10fea"
down_revision: Union[str, Sequence[str], None] = "2ce3a9eda463"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    account_type_enum = postgresql.ENUM(
        "savings", "current", "business", name="accounttype"
    )
    account_type_enum.create(op.get_bind(), checkfirst=True)
    id_type_enum = postgresql.ENUM(
        "voter_id", "national_id", "driver_licence", "other_id", name="idtype"
    )
    id_type_enum.create(op.get_bind(), checkfirst=True)
    verification_status_enum = postgresql.ENUM(
        "pending", "verified", "rejected", name="accountverification"
    )
    verification_status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column("store_accounts", sa.Column("bank_name", sa.String(), nullable=False))
    op.add_column(
        "store_accounts",
        sa.Column(
            "account_type",
            sa.Enum("savings", "current", "business", name="accounttype"),
            nullable=False,
        ),
    )
    op.add_column(
        "store_accounts",
        sa.Column(
            "type_of_id",
            sa.Enum(
                "voter_id", "national_id", "driver_license", "other_id", name="idtype"
            ),
            nullable=False,
        ),
    )
    op.add_column(
        "store_accounts",
        sa.Column(
            "verification_status",
            sa.Enum("pending", "verified", "rejected", name="accountverification"),
            nullable=False,
        ),
    )
    op.add_column(
        "store_accounts",
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "store_accounts", sa.Column("rejected_reason", sa.String(), nullable=True)
    )
    op.add_column(
        "store_accounts",
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "store_accounts",
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.alter_column(
        "store_accounts",
        "account_name",
        existing_type=postgresql.BYTEA(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.create_index(
        op.f("ix_store_accounts_verification_status"),
        "store_accounts",
        ["verification_status"],
        unique=False,
    )
    op.create_unique_constraint("unique_store_account", "store_accounts", ["store_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_store_account", "store_accounts", type_="unique")
    op.drop_index(
        op.f("ix_store_accounts_verification_status"), table_name="store_accounts"
    )
    op.alter_column(
        "store_accounts",
        "account_name",
        existing_type=sa.String(),
        type_=postgresql.BYTEA(),
        existing_nullable=False,
    )
    op.drop_column("store_accounts", "submitted_at")
    op.drop_column("store_accounts", "updated_at")
    op.drop_column("store_accounts", "rejected_reason")
    op.drop_column("store_accounts", "verified_at")
    op.drop_column("store_accounts", "verification_status")
    op.drop_column("store_accounts", "type_of_id")
    op.drop_column("store_accounts", "account_type")
    op.drop_column("store_accounts", "bank_name")
    # ### end Alembic commands ###
