"""add ProductVariant table

Revision ID: 0f6a13f89755
Revises: c2a20d56654c
Create Date: 2026-08-18 11:38:32.813270

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0f6a13f89755"
down_revision: Union[str, Sequence[str], None] = "c2a20d56654c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "productvariant",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("primary_image", sa.String(), nullable=False),
        sa.Column("sku", sa.String(), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sku"),
    )
    op.create_index(
        "idx_attributes",
        "productvariant",
        ["attributes"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_productvariant_product_id"),
        "productvariant",
        ["product_id"],
        unique=False,
    )
    op.create_table(
        "variantimage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("variant_id", sa.Integer(), nullable=False),
        sa.Column("image", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["productvariant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_variantimage_variant_id"), "variantimage", ["variant_id"], unique=False
    )
    op.add_column("inventory", sa.Column("variant_id", sa.Integer(), nullable=False))
    op.add_column("inventory", sa.Column("deleted_by", sa.Integer(), nullable=True))
    op.add_column(
        "inventory", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.drop_index(op.f("ix_inventory_product_id"), table_name="inventory")
    op.drop_constraint(op.f("store_product_inventory"), "inventory", type_="unique")
    op.create_unique_constraint(
        "uq_store_variant_inventory", "inventory", ["store_id", "variant_id"]
    )
    op.drop_constraint(
        op.f("inventory_product_id_fkey"), "inventory", type_="foreignkey"
    )
    op.create_foreign_key(None, "inventory", "productvariant", ["variant_id"], ["id"])
    op.drop_column("inventory", "product_id")
    op.add_column("product", sa.Column("updated_by", sa.Integer(), nullable=True))
    op.add_column(
        "product", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.alter_column(
        "product",
        "created_by",
        existing_type=sa.INTEGER(),
        server_default=None,
        nullable=False,
    )
    op.drop_index(op.f("ix_product_product_size"), table_name="product")
    op.drop_column("product", "product_price")
    op.drop_column("product", "product_type")
    op.drop_column("product", "product_size")
    op.drop_column("store", "created_by")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "store",
        sa.Column(
            "created_by",
            sa.INTEGER(),
            server_default=sa.text("1"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "product",
        sa.Column(
            "product_size",
            postgresql.ENUM(
                "small", "medium", "large", "extra_large", name="productsize"
            ),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "product",
        sa.Column("product_type", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "product",
        sa.Column(
            "product_price",
            sa.NUMERIC(precision=12, scale=2),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_index(
        op.f("ix_product_product_size"), "product", ["product_size"], unique=False
    )
    op.alter_column(
        "product",
        "created_by",
        existing_type=sa.INTEGER(),
        server_default=sa.text("1"),
        nullable=True,
    )
    op.drop_column("product", "deleted_at")
    op.drop_column("product", "updated_by")
    op.add_column(
        "inventory",
        sa.Column("product_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "inventory", type_="foreignkey")
    op.create_foreign_key(
        op.f("inventory_product_id_fkey"),
        "inventory",
        "product",
        ["product_id"],
        ["id"],
    )
    op.drop_constraint("uq_store_variant_inventory", "inventory", type_="unique")
    op.create_unique_constraint(
        op.f("store_product_inventory"),
        "inventory",
        ["store_id", "product_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("ix_inventory_product_id"), "inventory", ["product_id"], unique=False
    )
    op.drop_column("inventory", "deleted_at")
    op.drop_column("inventory", "deleted_by")
    op.drop_column("inventory", "variant_id")
    op.drop_index(op.f("ix_variantimage_variant_id"), table_name="variantimage")
    op.drop_table("variantimage")
    op.drop_index(op.f("ix_productvariant_product_id"), table_name="productvariant")
    op.drop_index("idx_attributes", table_name="productvariant", postgresql_using="gin")
    op.drop_table("productvariant")
    # ### end Alembic commands ###
