"""ensure nullability to last_event_id column in  refund table

Revision ID: 126151d4397f
Revises: dd70dff349bd
Create Date: 2026-06-08 17:29:59.159099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '126151d4397f'
down_revision: Union[str, Sequence[str], None] = 'dd70dff349bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refund', 'last_event_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('refund', 'last_event_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refund', 'last_event_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('refund', 'last_event_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
