"""add SubCategory Table

Revision ID: 151c303554e8
Revises: 1154a06deb79
Create Date: 2026-04-27 12:06:29.203830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '151c303554e8'
down_revision: Union[str, Sequence[str], None] = '1154a06deb79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subcategories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_subcategories_category_id'), 'subcategories', ['category_id'], unique=False)
    op.create_index(op.f('ix_subcategories_id'), 'subcategories', ['id'], unique=False)
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('products', sa.Column('subcategory_id', sa.Integer(), nullable=False))
    op.alter_column('products', 'store_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'product_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'image',
               existing_type=sa.VARCHAR(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('products', 'product_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('products', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'product_size',
               existing_type=postgresql.ENUM('small', 'medium', 'large', 'extra_large', name='productsize'),
               nullable=False)
    op.alter_column('products', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'product_availability',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_products_subcategory_id'), 'products', ['subcategory_id'], unique=False)
    op.create_foreign_key(None, 'products', 'subcategories', ['subcategory_id'], ['id'])
    op.add_column('stores', sa.Column('subcategory_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_stores_subcategory_id'), 'stores', ['subcategory_id'], unique=False)
    op.create_foreign_key(None, 'stores', 'subcategories', ['subcategory_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stores', type_='foreignkey')
    op.drop_index(op.f('ix_stores_subcategory_id'), table_name='stores')
    op.drop_column('stores', 'subcategory_id')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_subcategory_id'), table_name='products')
    op.alter_column('products', 'product_availability',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('products', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'product_size',
               existing_type=postgresql.ENUM('small', 'medium', 'large', 'extra_large', name='productsize'),
               nullable=True)
    op.alter_column('products', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('products', 'product_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('products', 'image',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('products', 'product_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('products', 'store_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('products', 'subcategory_id')
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_subcategories_id'), table_name='subcategories')
    op.drop_index(op.f('ix_subcategories_category_id'), table_name='subcategories')
    op.drop_table('subcategories')
    # ### end Alembic commands ###
