"""add nullable = True for member id column in order table

Revision ID: 171b71406659
Revises: c594b52ef3ba
Create Date: 2026-05-28 20:10:06.547447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '171b71406659'
down_revision: Union[str, Sequence[str], None] = 'c594b52ef3ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'member_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'member_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
