"""delete checkout column from order table

Revision ID: 1991198f7ad7
Revises: 3cc7c6379886
Create Date: 2026-06-03 15:57:22.754429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1991198f7ad7'
down_revision: Union[str, Sequence[str], None] = '3cc7c6379886'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'check_out')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('check_out', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
