"""add payment_status column to notification table

Revision ID: 1a3677ce04d8
Revises: c77f336c7052
Create Date: 2026-06-06 16:19:14.877279

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "1a3677ce04d8"
down_revision: Union[str, Sequence[str], None] = "c77f336c7052"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notification", sa.Column("payment_status", sa.String(), nullable=True)
    )
    op.drop_constraint(op.f("unique_order_paymennt"), "payment", type_="unique")
    op.create_unique_constraint("unique_order_payment", "payment", ["order_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_order_payment", "payment", type_="unique")
    op.create_unique_constraint(
        op.f("unique_order_paymennt"),
        "payment",
        ["order_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("notification", "payment_status")
    # ### end Alembic commands ###
