"""add store foreign key to productvariant table

Revision ID: 1c8fbf255f5b
Revises: 3c951fec336c
Create Date: 2026-09-02 15:58:35.389847

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "1c8fbf255f5b"
down_revision: Union[str, Sequence[str], None] = "3c951fec336c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "productvariant",
        "store_id",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_constraint(op.f("productvariant_sku_key"), "productvariant", type_="unique")
    op.create_index(
        op.f("ix_productvariant_sku"), "productvariant", ["sku"], unique=False
    )
    op.create_index(
        op.f("ix_productvariant_store_id"), "productvariant", ["store_id"], unique=False
    )
    op.create_unique_constraint("store_sku", "productvariant", ["store_id", "sku"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("store_sku", "productvariant", type_="unique")
    op.drop_index(op.f("ix_productvariant_store_id"), table_name="productvariant")
    op.drop_index(op.f("ix_productvariant_sku"), table_name="productvariant")
    op.create_unique_constraint(
        op.f("productvariant_sku_key"),
        "productvariant",
        ["sku"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "productvariant",
        "store_id",
        existing_type=sa.INTEGER(),
        server_default=sa.text("1"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
