"""add checkout_url column to payment table

Revision ID: 229495c5102e
Revises: 62aaf624f9f2
Create Date: 2026-06-05 11:42:44.248413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '229495c5102e'
down_revision: Union[str, Sequence[str], None] = '62aaf624f9f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('checkout_url', sa.String(), nullable=False))
    op.create_index(op.f('ix_payment_checkout_url'), 'payment', ['checkout_url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_checkout_url'), table_name='payment')
    op.drop_column('payment', 'checkout_url')
    # ### end Alembic commands ###
