"""refactor: account number, tax number, id number columnsto LargeBinary

Revision ID: 22cc84d4da52
Revises: 62762d730102
Create Date: 2026-03-29 14:36:13.026771

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "22cc84d4da52"
down_revision: Union[str, Sequence[str], None] = "62762d730102"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "store_accounts",
        "account_number",
        existing_type=sa.VARCHAR(),
        type_=sa.LargeBinary(),
        postgresql_using="account_number::bytea",
        existing_nullable=False,
    )
    op.alter_column(
        "store_accounts",
        "tax_identification_number",
        existing_type=sa.VARCHAR(),
        type_=sa.LargeBinary(),
        postgresql_using="tax_identification_number::bytea",
        existing_nullable=False,
    )
    op.alter_column(
        "store_accounts",
        "identification_number",
        existing_type=sa.VARCHAR(),
        type_=sa.LargeBinary(),
        postgresql_using="identification_number::bytea",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "store_accounts",
        "identification_number",
        existing_type=sa.LargeBinary(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.alter_column(
        "store_accounts",
        "tax_identification_number",
        existing_type=sa.LargeBinary(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.alter_column(
        "store_accounts",
        "account_number",
        existing_type=sa.LargeBinary(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
