"""add PostgreSQL ops to gin index

Revision ID: 23e640e5dc24
Revises: 623f775c7993
Create Date: 2026-08-19 20:31:22.041218

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "23e640e5dc24"
down_revision: Union[str, Sequence[str], None] = "623f775c7993"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("idx_searchable_text_ts"), table_name="store", postgresql_using="gin"
    )
    op.drop_index(
        op.f("idx_sub_category_gin"), table_name="store", postgresql_using="gin"
    )
    op.create_index(
        "idx_searchable_text",
        "store",
        ["searchable_text"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "idx_sub_category",
        "store",
        ["sub_category"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"sub_category": "jsonb_path_ops"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_sub_category",
        table_name="store",
        postgresql_using="gin",
        postgresql_ops={"sub_category": "jsonb_path_ops"},
    )
    op.drop_index("idx_searchable_text", table_name="store", postgresql_using="gin")
    op.create_index(
        op.f("idx_sub_category_gin"),
        "store",
        ["sub_category"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("idx_searchable_text_ts"),
        "store",
        ["searchable_text"],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###
