"""add variant_id foreign key to CartItem table

Revision ID: 2af22426ece8
Revises: 04f9df2766e9
Create Date: 2026-09-04 17:00:30.421088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2af22426ece8'
down_revision: Union[str, Sequence[str], None] = '04f9df2766e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cartitem', sa.Column('variant_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_cartitem_product_id'), table_name='cartitem')
    op.create_index(op.f('ix_cartitem_variant_id'), 'cartitem', ['variant_id'], unique=False)
    op.drop_constraint(op.f('cartitem_product_id_fkey'), 'cartitem', type_='foreignkey')
    op.create_foreign_key(None, 'cartitem', 'productvariant', ['variant_id'], ['id'])
    op.drop_column('cartitem', 'product_id')
    op.add_column('orderitem', sa.Column('variant_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_orderitem_product_id'), table_name='orderitem')
    op.create_index(op.f('ix_orderitem_variant_id'), 'orderitem', ['variant_id'], unique=False)
    op.drop_constraint(op.f('orderitem_product_id_fkey'), 'orderitem', type_='foreignkey')
    op.create_foreign_key(None, 'orderitem', 'productvariant', ['variant_id'], ['id'])
    op.drop_column('orderitem', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orderitem', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'orderitem', type_='foreignkey')
    op.create_foreign_key(op.f('orderitem_product_id_fkey'), 'orderitem', 'product', ['product_id'], ['id'])
    op.drop_index(op.f('ix_orderitem_variant_id'), table_name='orderitem')
    op.create_index(op.f('ix_orderitem_product_id'), 'orderitem', ['product_id'], unique=False)
    op.drop_column('orderitem', 'variant_id')
    op.add_column('cartitem', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cartitem', type_='foreignkey')
    op.create_foreign_key(op.f('cartitem_product_id_fkey'), 'cartitem', 'product', ['product_id'], ['id'])
    op.drop_index(op.f('ix_cartitem_variant_id'), table_name='cartitem')
    op.create_index(op.f('ix_cartitem_product_id'), 'cartitem', ['product_id'], unique=False)
    op.drop_column('cartitem', 'variant_id')
    # ### end Alembic commands ###
