"""remove refund_status column from refund table

Revision ID: 2c331b23f31f
Revises: 649533472e11
Create Date: 2026-04-18 17:58:39.522834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c331b23f31f'
down_revision: Union[str, Sequence[str], None] = '649533472e11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refunds_refund_status'), table_name='refunds')
    op.drop_column('refunds', 'refund_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refunds', sa.Column('refund_status', postgresql.ENUM('PARTIAL', 'FULL', name='refundstatus'), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_refunds_refund_status'), 'refunds', ['refund_status'], unique=False)
    # ### end Alembic commands ###
