"""change tax_identification_number to nullable = False

Revision ID: 2ce3a9eda463
Revises: 073fe2ae36ee
Create Date: 2026-05-12 14:26:48.414948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ce3a9eda463'
down_revision: Union[str, Sequence[str], None] = '073fe2ae36ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'avg_rating',
               existing_type=sa.NUMERIC(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('products', 'review_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('store_accounts', 'tax_identification_number',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    op.alter_column('stores', 'avg_rating',
               existing_type=sa.NUMERIC(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('stores', 'review_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stores', 'review_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('stores', 'avg_rating',
               existing_type=sa.NUMERIC(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('store_accounts', 'tax_identification_number',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    op.alter_column('products', 'review_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('products', 'avg_rating',
               existing_type=sa.NUMERIC(),
               nullable=True,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###
