"""add nullable = True to time_of_op column in notifications table

Revision ID: 2ef2d68f3dab
Revises: e0d927ca6b37
Create Date: 2026-05-23 18:52:48.879979

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2ef2d68f3dab"
down_revision: Union[str, Sequence[str], None] = "e0d927ca6b37"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("categories_name_key"), "categories", type_="unique")
    op.create_index(op.f("ix_categories_name"), "categories", ["name"], unique=True)
    op.alter_column(
        "notifications",
        "time_of_op",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.create_index(
        op.f("ix_products_product_name"), "products", ["product_name"], unique=False
    )
    op.drop_constraint(op.f("subcategories_name_key"), "subcategories", type_="unique")
    op.create_index(
        op.f("ix_subcategories_name"), "subcategories", ["name"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_subcategories_name"), table_name="subcategories")
    op.create_unique_constraint(
        op.f("subcategories_name_key"),
        "subcategories",
        ["name"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("store_accounts", "is_deleted")
    op.drop_index(op.f("ix_products_product_name"), table_name="products")
    op.alter_column(
        "notifications",
        "time_of_op",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.drop_index(op.f("ix_categories_name"), table_name="categories")
    op.create_unique_constraint(
        op.f("categories_name_key"),
        "categories",
        ["name"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
