"""add product size enum

Revision ID: 3128fbc2370c
Revises: 77297b60b57e
Create Date: 2026-04-08 18:11:57.218320

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3128fbc2370c"
down_revision: Union[str, Sequence[str], None] = "77297b60b57e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.dialects import postgresql

    product_size_enum = postgresql.ENUM(
        "small", "medium", "large", "extra_large", name="productsize"
    )
    product_size_enum.create(op.get_bind(), checkfirst=True)
    op.add_column("orders", sa.Column("reference_id", sa.String(), nullable=False))
    op.drop_index(op.f("ix_orders_refference_id"), table_name="orders")
    op.create_index(
        op.f("ix_orders_reference_id"), "orders", ["reference_id"], unique=True
    )
    op.drop_column("orders", "refference_id")
    op.add_column("payments", sa.Column("reference_id", sa.String(), nullable=False))
    op.drop_index(op.f("ix_payments_refference_id"), table_name="payments")
    op.create_index(
        op.f("ix_payments_reference_id"), "payments", ["reference_id"], unique=True
    )
    op.drop_column("payments", "refference_id")
    op.add_column(
        "products", sa.Column("product_description", sa.String(), nullable=True)
    )
    op.add_column(
        "products",
        sa.Column(
            "product_size",
            sa.Enum("small", "medium", "large", "extra_large", name="productsize"),
            nullable=True,
        ),
    )
    op.create_index(
        op.f("ix_products_product_size"), "products", ["product_size"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_products_product_size"), table_name="products")
    op.drop_column("products", "product_size")
    op.drop_column("products", "product_description")
    op.add_column(
        "payments",
        sa.Column("refference_id", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_index(op.f("ix_payments_reference_id"), table_name="payments")
    op.create_index(
        op.f("ix_payments_refference_id"), "payments", ["refference_id"], unique=True
    )
    op.drop_column("payments", "reference_id")
    op.add_column(
        "orders",
        sa.Column("refference_id", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_index(op.f("ix_orders_reference_id"), table_name="orders")
    op.create_index(
        op.f("ix_orders_refference_id"), "orders", ["refference_id"], unique=True
    )
    op.drop_column("orders", "reference_id")
    # ### end Alembic commands ###
