"""add updated at column in Ticket table

Revision ID: 312cdbe11b38
Revises: 9bbcfd419f83
Create Date: 2026-04-20 19:54:44.893480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '312cdbe11b38'
down_revision: Union[str, Sequence[str], None] = '9bbcfd419f83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_tickets_assigned_to'), 'tickets', ['assigned_to'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_assigned_to'), table_name='tickets')
    op.drop_column('tickets', 'updated_at')
    # ### end Alembic commands ###
