"""change table names to singular

Revision ID: 31eea10f4332
Revises: 
Create Date: 2026-05-23 23:33:59.268747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '31eea10f4332'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_id'), 'category', ['id'], unique=False)
    op.create_index(op.f('ix_category_is_deleted'), 'category', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=True)
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification', sa.String(), nullable=False),
    sa.Column('from_user', sa.Integer(), nullable=False),
    sa.Column('notified_user', sa.Integer(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('time_of_op', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_from_user'), 'notification', ['from_user'], unique=False)
    op.create_index(op.f('ix_notification_id'), 'notification', ['id'], unique=False)
    op.create_index(op.f('ix_notification_notified_user'), 'notification', ['notified_user'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('nationality', sa.String(), nullable=False),
    sa.Column('profile_picture', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_role'), 'user', ['role'], unique=False)
    op.create_index(op.f('ix_user_surname'), 'user', ['surname'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    op.create_table('store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_logo', sa.String(), nullable=True),
    sa.Column('store_photo', sa.String(), nullable=False),
    sa.Column('store_name', sa.String(), nullable=False),
    sa.Column('motto', sa.String(), nullable=True),
    sa.Column('edited_name', sa.Boolean(), nullable=False),
    sa.Column('store_previous_name', sa.String(), nullable=True),
    sa.Column('store_description', sa.String(), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('category_name', sa.String(), nullable=False),
    sa.Column('sub_category', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('avg_rating', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('store_email', sa.String(), nullable=True),
    sa.Column('shipping_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('store_contact', sa.String(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('founded', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_approved'), 'store', ['approved'], unique=False)
    op.create_index(op.f('ix_store_category_id'), 'store', ['category_id'], unique=False)
    op.create_index(op.f('ix_store_category_name'), 'store', ['category_name'], unique=False)
    op.create_index(op.f('ix_store_id'), 'store', ['id'], unique=False)
    op.create_index(op.f('ix_store_is_deleted'), 'store', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_store_slug'), 'store', ['slug'], unique=True)
    op.create_index(op.f('ix_store_store_name'), 'store', ['store_name'], unique=True)
    op.create_index(op.f('ix_store_sub_category'), 'store', ['sub_category'], unique=False)
    op.create_table('subcategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subcategory_category_id'), 'subcategory', ['category_id'], unique=False)
    op.create_index(op.f('ix_subcategory_id'), 'subcategory', ['id'], unique=False)
    op.create_index(op.f('ix_subcategory_is_deleted'), 'subcategory', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_subcategory_name'), 'subcategory', ['name'], unique=True)
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_progress', 'closed', name='ticketstatus'), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_assigned_to'), 'ticket', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_ticket_id'), 'ticket', ['id'], unique=False)
    op.create_index(op.f('ix_ticket_status'), 'ticket', ['status'], unique=False)
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('street', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_address_is_deleted'), 'address', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_address_store_id'), 'address', ['store_id'], unique=False)
    op.create_table('membership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('membership_type', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_pause', sa.Boolean(), nullable=True),
    sa.Column('pause_date', sa.Date(), nullable=True),
    sa.Column('delete_date', sa.Date(), nullable=True),
    sa.Column('reactivation_date', sa.Date(), nullable=True),
    sa.Column('start_date', sa.Date(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'store_id', name='user_store_membership')
    )
    op.create_index(op.f('ix_membership_id'), 'membership', ['id'], unique=False)
    op.create_index(op.f('ix_membership_is_active'), 'membership', ['is_active'], unique=False)
    op.create_index(op.f('ix_membership_is_deleted'), 'membership', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_membership_is_pause'), 'membership', ['is_pause'], unique=False)
    op.create_index(op.f('ix_membership_membership_type'), 'membership', ['membership_type'], unique=False)
    op.create_index(op.f('ix_membership_store_id'), 'membership', ['store_id'], unique=False)
    op.create_index(op.f('ix_membership_user_id'), 'membership', ['user_id'], unique=False)
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('support_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('pics', sa.String(), nullable=True),
    sa.Column('delivered', sa.Boolean(), nullable=True),
    sa.Column('seen', sa.Boolean(), nullable=True),
    sa.Column('sender_deleted', sa.Boolean(), nullable=True),
    sa.Column('receiver_deleted', sa.Boolean(), nullable=True),
    sa.Column('time_of_chat', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_customer_id'), 'message', ['customer_id'], unique=False)
    op.create_index(op.f('ix_message_id'), 'message', ['id'], unique=False)
    op.create_index(op.f('ix_message_receiver_deleted'), 'message', ['receiver_deleted'], unique=False)
    op.create_index(op.f('ix_message_sender_deleted'), 'message', ['sender_deleted'], unique=False)
    op.create_index(op.f('ix_message_support_id'), 'message', ['support_id'], unique=False)
    op.create_index(op.f('ix_message_ticket_id'), 'message', ['ticket_id'], unique=False)
    op.create_index(op.f('ix_message_user_id'), 'message', ['user_id'], unique=False)
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('primary_image', sa.String(), nullable=False),
    sa.Column('product_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('product_type', sa.String(), nullable=False),
    sa.Column('avg_rating', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('product_description', sa.Text(), nullable=False),
    sa.Column('product_size', sa.Enum('small', 'medium', 'large', 'extra_large', name='productsize'), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('sub_category_id', sa.Integer(), nullable=False),
    sa.Column('product_availability', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.ForeignKeyConstraint(['sub_category_id'], ['subcategory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_category_id'), 'product', ['category_id'], unique=False)
    op.create_index(op.f('ix_product_id'), 'product', ['id'], unique=False)
    op.create_index(op.f('ix_product_product_name'), 'product', ['product_name'], unique=False)
    op.create_index(op.f('ix_product_product_size'), 'product', ['product_size'], unique=False)
    op.create_index(op.f('ix_product_store_id'), 'product', ['store_id'], unique=False)
    op.create_index(op.f('ix_product_sub_category_id'), 'product', ['sub_category_id'], unique=False)
    op.create_table('store_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.String(), nullable=False),
    sa.Column('account_holder_name', sa.String(), nullable=False),
    sa.Column('account_type', sa.Enum('savings', 'current', 'business', name='accounttype'), nullable=False),
    sa.Column('type_of_id', sa.Enum('voter_id', 'national_id', 'driver_license', 'other_id', name='idtype'), nullable=False),
    sa.Column('account_number', sa.LargeBinary(), nullable=False),
    sa.Column('tax_identification_number', sa.LargeBinary(), nullable=True),
    sa.Column('identification_number', sa.LargeBinary(), nullable=False),
    sa.Column('verification_status', sa.Enum('pending', 'verified', 'rejected', name='accountverification'), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_reason', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(rejected_reason IS NULL) OR (verification_status = 'rejected')", name='rejection_reason_check'),
    sa.CheckConstraint("(verification_status != 'verified') OR (verified_at IS NOT NULL)", name='verified_account_timestamp_check'),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', name='unique_store_account')
    )
    op.create_index(op.f('ix_store_account_id'), 'store_account', ['id'], unique=False)
    op.create_index(op.f('ix_store_account_store_id'), 'store_account', ['store_id'], unique=False)
    op.create_index(op.f('ix_store_account_verification_status'), 'store_account', ['verification_status'], unique=False)
    op.create_table('store_owners',
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('stores_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stores_id'], ['store.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('users_id', 'stores_id')
    )
    op.create_index(op.f('ix_store_owners_stores_id'), 'store_owners', ['stores_id'], unique=False)
    op.create_index(op.f('ix_store_owners_users_id'), 'store_owners', ['users_id'], unique=False)
    op.create_table('store_staffs',
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('stores_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stores_id'], ['store.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('users_id', 'stores_id')
    )
    op.create_index(op.f('ix_store_staffs_stores_id'), 'store_staffs', ['stores_id'], unique=False)
    op.create_index(op.f('ix_store_staffs_users_id'), 'store_staffs', ['users_id'], unique=False)
    op.create_table('cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('check_out', sa.Boolean(), nullable=False),
    sa.Column('total_quantity', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['membership.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cart_check_out'), 'cart', ['check_out'], unique=False)
    op.create_index(op.f('ix_cart_created_at'), 'cart', ['created_at'], unique=False)
    op.create_index(op.f('ix_cart_id'), 'cart', ['id'], unique=False)
    op.create_index(op.f('ix_cart_member_id'), 'cart', ['member_id'], unique=False)
    op.create_index(op.f('ix_cart_store_id'), 'cart', ['store_id'], unique=False)
    op.create_index(op.f('ix_cart_user_id'), 'cart', ['user_id'], unique=False)
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('stock_quantity >= 0', name='positive_quantity'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'product_id', name='store_product_inventory')
    )
    op.create_index(op.f('ix_inventory_id'), 'inventory', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_product_id'), 'inventory', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_store_id'), 'inventory', ['store_id'], unique=False)
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('delivery_address_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('total_quantity', sa.Float(), nullable=False),
    sa.Column('delivery_address', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('order_delete', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'shipped', 'delivered', 'cancelled', name='orderstatus'), nullable=False),
    sa.Column('check_out', sa.Boolean(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('shipping_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reference_id', sa.String(), nullable=False),
    sa.Column('check_out_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['delivery_address_id'], ['address.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['member_id'], ['membership.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_check_out_time'), 'order', ['check_out_time'], unique=False)
    op.create_index(op.f('ix_order_created_at'), 'order', ['created_at'], unique=False)
    op.create_index(op.f('ix_order_delivery_address_id'), 'order', ['delivery_address_id'], unique=False)
    op.create_index(op.f('ix_order_id'), 'order', ['id'], unique=False)
    op.create_index(op.f('ix_order_member_id'), 'order', ['member_id'], unique=False)
    op.create_index(op.f('ix_order_reference_id'), 'order', ['reference_id'], unique=True)
    op.create_index(op.f('ix_order_status'), 'order', ['status'], unique=False)
    op.create_index(op.f('ix_order_store_id'), 'order', ['store_id'], unique=False)
    op.create_index(op.f('ix_order_user_id'), 'order', ['user_id'], unique=False)
    op.create_table('product_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_image_id'), 'product_image', ['id'], unique=False)
    op.create_index(op.f('ix_product_image_product_id'), 'product_image', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_image_store_id'), 'product_image', ['store_id'], unique=False)
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('review_text', sa.String(), nullable=True),
    sa.Column('ratings', sa.Integer(), nullable=True),
    sa.Column('product_reply_count', sa.Integer(), nullable=False),
    sa.Column('store_reply_count', sa.Integer(), nullable=False),
    sa.Column('product_review_reaction_count', sa.Integer(), nullable=False),
    sa.Column('store_review_reaction_count', sa.Integer(), nullable=False),
    sa.Column('edited', sa.Boolean(), nullable=True),
    sa.Column('time_of_post', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'product_id', name='user_product_review'),
    sa.UniqueConstraint('user_id', 'store_id', name='user_store_review')
    )
    op.create_index(op.f('ix_review_id'), 'review', ['id'], unique=False)
    op.create_index(op.f('ix_review_product_id'), 'review', ['product_id'], unique=False)
    op.create_index(op.f('ix_review_store_id'), 'review', ['store_id'], unique=False)
    op.create_index(op.f('ix_review_time_of_post'), 'review', ['time_of_post'], unique=False)
    op.create_index(op.f('ix_review_user_id'), 'review', ['user_id'], unique=False)
    op.create_table('subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('membership_id', sa.Integer(), nullable=False),
    sa.Column('plan_name', sa.Enum('Standard', 'Premium', 'Regular', name='subscriptionplan'), nullable=False),
    sa.Column('price_id', sa.String(), nullable=True),
    sa.Column('plan_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('reference_id', sa.String(), nullable=False),
    sa.Column('last_event_id', sa.String(), nullable=False),
    sa.Column('last_event_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expire_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_of_subscription', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['membership_id'], ['membership.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_expire_at'), 'subscription', ['expire_at'], unique=False)
    op.create_index(op.f('ix_subscription_id'), 'subscription', ['id'], unique=False)
    op.create_index(op.f('ix_subscription_last_event_at'), 'subscription', ['last_event_at'], unique=False)
    op.create_index(op.f('ix_subscription_last_event_id'), 'subscription', ['last_event_id'], unique=False)
    op.create_index(op.f('ix_subscription_membership_id'), 'subscription', ['membership_id'], unique=False)
    op.create_index(op.f('ix_subscription_plan_name'), 'subscription', ['plan_name'], unique=False)
    op.create_index(op.f('ix_subscription_reference_id'), 'subscription', ['reference_id'], unique=False)
    op.create_index(op.f('ix_subscription_status'), 'subscription', ['status'], unique=False)
    op.create_table('cartitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cartitem_cart_id'), 'cartitem', ['cart_id'], unique=False)
    op.create_index(op.f('ix_cartitem_id'), 'cartitem', ['id'], unique=False)
    op.create_index(op.f('ix_cartitem_product_id'), 'cartitem', ['product_id'], unique=False)
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', 'REFUNDED', name='paymentstatus'), nullable=False),
    sa.Column('reference_id', sa.String(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('shipping_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_event_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_id'), 'payment', ['id'], unique=False)
    op.create_index(op.f('ix_payment_last_event_id'), 'payment', ['last_event_id'], unique=False)
    op.create_index(op.f('ix_payment_order_id'), 'payment', ['order_id'], unique=False)
    op.create_index(op.f('ix_payment_payment_status'), 'payment', ['payment_status'], unique=False)
    op.create_index(op.f('ix_payment_reference_id'), 'payment', ['reference_id'], unique=True)
    op.create_index(op.f('ix_payment_transaction_id'), 'payment', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_payment_user_id'), 'payment', ['user_id'], unique=False)
    op.create_table('reply',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('edited', sa.Boolean(), nullable=True),
    sa.Column('review_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('reply_text', sa.String(), nullable=True),
    sa.Column('product_reply_reaction_count', sa.Integer(), nullable=False),
    sa.Column('store_reply_reaction_count', sa.Integer(), nullable=False),
    sa.Column('time_of_post', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['review_id'], ['review.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reply_id'), 'reply', ['id'], unique=False)
    op.create_index(op.f('ix_reply_product_id'), 'reply', ['product_id'], unique=False)
    op.create_index(op.f('ix_reply_review_id'), 'reply', ['review_id'], unique=False)
    op.create_index(op.f('ix_reply_store_id'), 'reply', ['store_id'], unique=False)
    op.create_index(op.f('ix_reply_user_id'), 'reply', ['user_id'], unique=False)
    op.create_table('orderitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('cartitem_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['cartitem_id'], ['cartitem.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orderitem_cartitem_id'), 'orderitem', ['cartitem_id'], unique=False)
    op.create_index(op.f('ix_orderitem_id'), 'orderitem', ['id'], unique=False)
    op.create_index(op.f('ix_orderitem_order_id'), 'orderitem', ['order_id'], unique=False)
    op.create_table('react',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('like', 'love', 'wow', 'laugh', 'sad', 'angry', name='reactiontype'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reply_id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('time_of_reaction', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(reply_id IS NULL AND review_id IS NOT NULL) OR (reply_id IS NOT NULL AND review_id IS NULL)', name='exactly_one_parent'),
    sa.ForeignKeyConstraint(['reply_id'], ['reply.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_id'], ['review.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'reply_id', name='unique_reply_react'),
    sa.UniqueConstraint('user_id', 'review_id', name='unique_review_react')
    )
    op.create_index(op.f('ix_react_id'), 'react', ['id'], unique=False)
    op.create_index(op.f('ix_react_reply_id'), 'react', ['reply_id'], unique=False)
    op.create_index(op.f('ix_react_review_id'), 'react', ['review_id'], unique=False)
    op.create_index(op.f('ix_react_time_of_reaction'), 'react', ['time_of_reaction'], unique=False)
    op.create_index(op.f('ix_react_user_id'), 'react', ['user_id'], unique=False)
    op.create_table('refund',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('refund_id', sa.String(), nullable=False),
    sa.Column('refund_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('refund_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_event_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refund_id'), 'refund', ['id'], unique=False)
    op.create_index(op.f('ix_refund_last_event_id'), 'refund', ['last_event_id'], unique=False)
    op.create_index(op.f('ix_refund_order_id'), 'refund', ['order_id'], unique=False)
    op.create_index(op.f('ix_refund_payment_id'), 'refund', ['payment_id'], unique=False)
    op.create_index(op.f('ix_refund_refund_id'), 'refund', ['refund_id'], unique=True)
    op.create_index(op.f('ix_refund_user_id'), 'refund', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refund_user_id'), table_name='refund')
    op.drop_index(op.f('ix_refund_refund_id'), table_name='refund')
    op.drop_index(op.f('ix_refund_payment_id'), table_name='refund')
    op.drop_index(op.f('ix_refund_order_id'), table_name='refund')
    op.drop_index(op.f('ix_refund_last_event_id'), table_name='refund')
    op.drop_index(op.f('ix_refund_id'), table_name='refund')
    op.drop_table('refund')
    op.drop_index(op.f('ix_react_user_id'), table_name='react')
    op.drop_index(op.f('ix_react_time_of_reaction'), table_name='react')
    op.drop_index(op.f('ix_react_review_id'), table_name='react')
    op.drop_index(op.f('ix_react_reply_id'), table_name='react')
    op.drop_index(op.f('ix_react_id'), table_name='react')
    op.drop_table('react')
    op.drop_index(op.f('ix_orderitem_order_id'), table_name='orderitem')
    op.drop_index(op.f('ix_orderitem_id'), table_name='orderitem')
    op.drop_index(op.f('ix_orderitem_cartitem_id'), table_name='orderitem')
    op.drop_table('orderitem')
    op.drop_index(op.f('ix_reply_user_id'), table_name='reply')
    op.drop_index(op.f('ix_reply_store_id'), table_name='reply')
    op.drop_index(op.f('ix_reply_review_id'), table_name='reply')
    op.drop_index(op.f('ix_reply_product_id'), table_name='reply')
    op.drop_index(op.f('ix_reply_id'), table_name='reply')
    op.drop_table('reply')
    op.drop_index(op.f('ix_payment_user_id'), table_name='payment')
    op.drop_index(op.f('ix_payment_transaction_id'), table_name='payment')
    op.drop_index(op.f('ix_payment_reference_id'), table_name='payment')
    op.drop_index(op.f('ix_payment_payment_status'), table_name='payment')
    op.drop_index(op.f('ix_payment_order_id'), table_name='payment')
    op.drop_index(op.f('ix_payment_last_event_id'), table_name='payment')
    op.drop_index(op.f('ix_payment_id'), table_name='payment')
    op.drop_table('payment')
    op.drop_index(op.f('ix_cartitem_product_id'), table_name='cartitem')
    op.drop_index(op.f('ix_cartitem_id'), table_name='cartitem')
    op.drop_index(op.f('ix_cartitem_cart_id'), table_name='cartitem')
    op.drop_table('cartitem')
    op.drop_index(op.f('ix_subscription_status'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_reference_id'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_plan_name'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_membership_id'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_last_event_id'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_last_event_at'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_id'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_expire_at'), table_name='subscription')
    op.drop_table('subscription')
    op.drop_index(op.f('ix_review_user_id'), table_name='review')
    op.drop_index(op.f('ix_review_time_of_post'), table_name='review')
    op.drop_index(op.f('ix_review_store_id'), table_name='review')
    op.drop_index(op.f('ix_review_product_id'), table_name='review')
    op.drop_index(op.f('ix_review_id'), table_name='review')
    op.drop_table('review')
    op.drop_index(op.f('ix_product_image_store_id'), table_name='product_image')
    op.drop_index(op.f('ix_product_image_product_id'), table_name='product_image')
    op.drop_index(op.f('ix_product_image_id'), table_name='product_image')
    op.drop_table('product_image')
    op.drop_index(op.f('ix_order_user_id'), table_name='order')
    op.drop_index(op.f('ix_order_store_id'), table_name='order')
    op.drop_index(op.f('ix_order_status'), table_name='order')
    op.drop_index(op.f('ix_order_reference_id'), table_name='order')
    op.drop_index(op.f('ix_order_member_id'), table_name='order')
    op.drop_index(op.f('ix_order_id'), table_name='order')
    op.drop_index(op.f('ix_order_delivery_address_id'), table_name='order')
    op.drop_index(op.f('ix_order_created_at'), table_name='order')
    op.drop_index(op.f('ix_order_check_out_time'), table_name='order')
    op.drop_table('order')
    op.drop_index(op.f('ix_inventory_store_id'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_product_id'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_id'), table_name='inventory')
    op.drop_table('inventory')
    op.drop_index(op.f('ix_cart_user_id'), table_name='cart')
    op.drop_index(op.f('ix_cart_store_id'), table_name='cart')
    op.drop_index(op.f('ix_cart_member_id'), table_name='cart')
    op.drop_index(op.f('ix_cart_id'), table_name='cart')
    op.drop_index(op.f('ix_cart_created_at'), table_name='cart')
    op.drop_index(op.f('ix_cart_check_out'), table_name='cart')
    op.drop_table('cart')
    op.drop_index(op.f('ix_store_staffs_users_id'), table_name='store_staffs')
    op.drop_index(op.f('ix_store_staffs_stores_id'), table_name='store_staffs')
    op.drop_table('store_staffs')
    op.drop_index(op.f('ix_store_owners_users_id'), table_name='store_owners')
    op.drop_index(op.f('ix_store_owners_stores_id'), table_name='store_owners')
    op.drop_table('store_owners')
    op.drop_index(op.f('ix_store_account_verification_status'), table_name='store_account')
    op.drop_index(op.f('ix_store_account_store_id'), table_name='store_account')
    op.drop_index(op.f('ix_store_account_id'), table_name='store_account')
    op.drop_table('store_account')
    op.drop_index(op.f('ix_product_sub_category_id'), table_name='product')
    op.drop_index(op.f('ix_product_store_id'), table_name='product')
    op.drop_index(op.f('ix_product_product_size'), table_name='product')
    op.drop_index(op.f('ix_product_product_name'), table_name='product')
    op.drop_index(op.f('ix_product_id'), table_name='product')
    op.drop_index(op.f('ix_product_category_id'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_message_user_id'), table_name='message')
    op.drop_index(op.f('ix_message_ticket_id'), table_name='message')
    op.drop_index(op.f('ix_message_support_id'), table_name='message')
    op.drop_index(op.f('ix_message_sender_deleted'), table_name='message')
    op.drop_index(op.f('ix_message_receiver_deleted'), table_name='message')
    op.drop_index(op.f('ix_message_id'), table_name='message')
    op.drop_index(op.f('ix_message_customer_id'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_membership_user_id'), table_name='membership')
    op.drop_index(op.f('ix_membership_store_id'), table_name='membership')
    op.drop_index(op.f('ix_membership_membership_type'), table_name='membership')
    op.drop_index(op.f('ix_membership_is_pause'), table_name='membership')
    op.drop_index(op.f('ix_membership_is_deleted'), table_name='membership')
    op.drop_index(op.f('ix_membership_is_active'), table_name='membership')
    op.drop_index(op.f('ix_membership_id'), table_name='membership')
    op.drop_table('membership')
    op.drop_index(op.f('ix_address_store_id'), table_name='address')
    op.drop_index(op.f('ix_address_is_deleted'), table_name='address')
    op.drop_table('address')
    op.drop_index(op.f('ix_ticket_status'), table_name='ticket')
    op.drop_index(op.f('ix_ticket_id'), table_name='ticket')
    op.drop_index(op.f('ix_ticket_assigned_to'), table_name='ticket')
    op.drop_table('ticket')
    op.drop_index(op.f('ix_subcategory_name'), table_name='subcategory')
    op.drop_index(op.f('ix_subcategory_is_deleted'), table_name='subcategory')
    op.drop_index(op.f('ix_subcategory_id'), table_name='subcategory')
    op.drop_index(op.f('ix_subcategory_category_id'), table_name='subcategory')
    op.drop_table('subcategory')
    op.drop_index(op.f('ix_store_sub_category'), table_name='store')
    op.drop_index(op.f('ix_store_store_name'), table_name='store')
    op.drop_index(op.f('ix_store_slug'), table_name='store')
    op.drop_index(op.f('ix_store_is_deleted'), table_name='store')
    op.drop_index(op.f('ix_store_id'), table_name='store')
    op.drop_index(op.f('ix_store_category_name'), table_name='store')
    op.drop_index(op.f('ix_store_category_id'), table_name='store')
    op.drop_index(op.f('ix_store_approved'), table_name='store')
    op.drop_table('store')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_surname'), table_name='user')
    op.drop_index(op.f('ix_user_role'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_first_name'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_notification_notified_user'), table_name='notification')
    op.drop_index(op.f('ix_notification_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_from_user'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.drop_index(op.f('ix_category_is_deleted'), table_name='category')
    op.drop_index(op.f('ix_category_id'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
