"""add slug and desciption to store table

Revision ID: 324c275e1546
Revises: 81c32982a40a
Create Date: 2026-03-23 18:53:19.823352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '324c275e1546'
down_revision: Union[str, Sequence[str], None] = '81c32982a40a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('business_logo', sa.String(), nullable=True))
    op.add_column('stores', sa.Column('store_description', sa.String(), nullable=False))
    op.add_column('stores', sa.Column('slug', sa.String(length=255), nullable=False))
    op.drop_constraint(op.f('stores_store_name_key'), 'stores', type_='unique')
    op.create_index(op.f('ix_stores_approved'), 'stores', ['approved'], unique=False)
    op.create_index(op.f('ix_stores_business_type'), 'stores', ['business_type'], unique=False)
    op.create_index(op.f('ix_stores_is_deleted'), 'stores', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_stores_slug'), 'stores', ['slug'], unique=True)
    op.create_index(op.f('ix_stores_store_name'), 'stores', ['store_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stores_store_name'), table_name='stores')
    op.drop_index(op.f('ix_stores_slug'), table_name='stores')
    op.drop_index(op.f('ix_stores_is_deleted'), table_name='stores')
    op.drop_index(op.f('ix_stores_business_type'), table_name='stores')
    op.drop_index(op.f('ix_stores_approved'), table_name='stores')
    op.create_unique_constraint(op.f('stores_store_name_key'), 'stores', ['store_name'], postgresql_nulls_not_distinct=False)
    op.drop_column('stores', 'slug')
    op.drop_column('stores', 'store_description')
    op.drop_column('stores', 'business_logo')
    # ### end Alembic commands ###
