"""delete check out time column from order table

Revision ID: 337b04d5d33e
Revises: 81c68553bfca
Create Date: 2026-06-01 12:04:32.440928

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "337b04d5d33e"
down_revision: Union[str, Sequence[str], None] = "81c68553bfca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order",
        sa.Column("tax_amount", sa.Numeric(precision=12, scale=2), nullable=True),
    )
    op.add_column(
        "order", sa.Column("re_order_time", sa.DateTime(timezone=True), nullable=True)
    )
    op.drop_index(op.f("ix_order_check_out_time"), table_name="order")
    op.create_index(
        op.f("ix_order_re_order_time"), "order", ["re_order_time"], unique=False
    )
    op.drop_column("order", "check_out_time")
    op.add_column(
        "payment",
        sa.Column("tax_amount", sa.Numeric(precision=12, scale=2), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("payment", "tax_amount")
    op.add_column(
        "order",
        sa.Column(
            "check_out_time",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_index(op.f("ix_order_re_order_time"), table_name="order")
    op.create_index(
        op.f("ix_order_check_out_time"), "order", ["check_out_time"], unique=False
    )
    op.drop_column("order", "re_order_time")
    op.drop_column("order", "tax_amount")
    # ### end Alembic commands ###
