"""add reaction count column in review and reply table

Revision ID: 365a37ba352b
Revises: 5461c335ac92
Create Date: 2026-04-07 15:51:25.294277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '365a37ba352b'
down_revision: Union[str, Sequence[str], None] = '5461c335ac92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('like', 'love', 'wow', 'laugh', 'sad', 'angry', name='reactiontype'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reply_id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('time_of_reaction', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(reply_id IS NULL AND review_id IS NOT NULL) OR (reply_id IS NOT NULL AND review_id IS NULL)', name='exactly_one_parent'),
    sa.ForeignKeyConstraint(['reply_id'], ['replies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'reply_id', name='unique_reply_react'),
    sa.UniqueConstraint('user_id', 'review_id', name='unique_review_react')
    )
    op.create_index(op.f('ix_reacts_id'), 'reacts', ['id'], unique=False)
    op.create_index(op.f('ix_reacts_reply_id'), 'reacts', ['reply_id'], unique=False)
    op.create_index(op.f('ix_reacts_review_id'), 'reacts', ['review_id'], unique=False)
    op.create_index(op.f('ix_reacts_time_of_reaction'), 'reacts', ['time_of_reaction'], unique=False)
    op.create_index(op.f('ix_reacts_user_id'), 'reacts', ['user_id'], unique=False)
    op.add_column('replies', sa.Column('product_reply_reaction_count', sa.Integer(), nullable=False))
    op.add_column('replies', sa.Column('store_reply_reaction_count', sa.Integer(), nullable=False))
    op.add_column('reviews', sa.Column('product_review_reaction_count', sa.Integer(), nullable=False))
    op.add_column('reviews', sa.Column('store_review_reaction_count', sa.Integer(), nullable=False))
    op.create_unique_constraint('user_product_review', 'reviews', ['user_id', 'product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_product_review', 'reviews', type_='unique')
    op.drop_column('reviews', 'store_review_reaction_count')
    op.drop_column('reviews', 'product_review_reaction_count')
    op.drop_column('replies', 'store_reply_reaction_count')
    op.drop_column('replies', 'product_reply_reaction_count')
    op.drop_index(op.f('ix_reacts_user_id'), table_name='reacts')
    op.drop_index(op.f('ix_reacts_time_of_reaction'), table_name='reacts')
    op.drop_index(op.f('ix_reacts_review_id'), table_name='reacts')
    op.drop_index(op.f('ix_reacts_reply_id'), table_name='reacts')
    op.drop_index(op.f('ix_reacts_id'), table_name='reacts')
    op.drop_table('reacts')
    # ### end Alembic commands ###
