"""ensure tax_rate column is not nullable in store table

Revision ID: 3cc7c6379886
Revises: 337b04d5d33e
Create Date: 2026-06-01 16:28:58.524526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cc7c6379886'
down_revision: Union[str, Sequence[str], None] = '337b04d5d33e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
