"""add payment status enum

Revision ID: 41d131baa011
Revises: 365a37ba352b
Create Date: 2026-04-08 17:24:21.536695

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "41d131baa011"
down_revision: Union[str, Sequence[str], None] = "365a37ba352b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.dialects import postgresql

    payment_enums = postgresql.ENUM(
        "PENDING", "SUCCESS", "FAILED", "REFUNDED", name="paymentstatus"
    )
    payment_enums.create(op.get_bind())
    op.add_column("payments", sa.Column("refference_id", sa.String(), nullable=False))
    op.add_column(
        "payments",
        sa.Column("tax_amount", sa.Numeric(precision=10, scale=2), nullable=False),
    )
    op.alter_column(
        "payments",
        "payment_status",
        existing_type=sa.VARCHAR(),
        type_=sa.Enum("PENDING", "SUCCESS", "FAILED", "REFUNDED", name="paymentstatus"),
        existing_nullable=False,
        postgresql_using="payment_status::paymentstatus",
    )
    op.create_index(
        op.f("ix_payments_refference_id"), "payments", ["refference_id"], unique=True
    )
    op.drop_column("payments", "tax")
    op.drop_column("payments", "discount")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "payments",
        sa.Column(
            "discount",
            sa.NUMERIC(precision=10, scale=2),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "payments",
        sa.Column(
            "tax",
            sa.NUMERIC(precision=10, scale=2),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_index(op.f("ix_payments_refference_id"), table_name="payments")
    op.alter_column(
        "payments",
        "payment_status",
        existing_type=sa.Enum(
            "PENDING", "SUCCESS", "FAILED", "REFUNDED", name="paymentstatus"
        ),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.drop_column("payments", "tax_amount")
    op.drop_column("payments", "refference_id")
    # ### end Alembic commands ###
