"""add subscription table

Revision ID: 4262bad5abba
Revises: 3128fbc2370c
Create Date: 2026-04-10 13:15:15.727013

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4262bad5abba"
down_revision: Union[str, Sequence[str], None] = "3128fbc2370c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("membership_id", sa.Integer(), nullable=False),
        sa.Column(
            "plan_name",
            sa.Enum("Standard", "Premium", "Regular", name="subscriptionplan"),
            nullable=False,
        ),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "expire_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now() + INTERVAL '30 days'"),
            nullable=False,
        ),
        sa.Column(
            "time_of_subscription",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["membership_id"],
            ["memberships.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_subscriptions_id"), "subscriptions", ["id"], unique=False)
    op.create_index(
        op.f("ix_subscriptions_membership_id"),
        "subscriptions",
        ["membership_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subscriptions_plan_name"), "subscriptions", ["plan_name"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_subscriptions_plan_name"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_membership_id"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_id"), table_name="subscriptions")
    op.drop_table("subscriptions")
    # ### end Alembic commands ###
