"""add state, country to store address table

Revision ID: 42a262fb2250
Revises: 22cc84d4da52
Create Date: 2026-03-29 15:33:25.456581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42a262fb2250'
down_revision: Union[str, Sequence[str], None] = '22cc84d4da52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_addresses', sa.Column('street', sa.String(), nullable=False))
    op.add_column('store_addresses', sa.Column('city', sa.String(), nullable=False))
    op.add_column('store_addresses', sa.Column('state', sa.String(), nullable=False))
    op.add_column('store_addresses', sa.Column('country', sa.String(), nullable=False))
    op.drop_column('store_addresses', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_addresses', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('store_addresses', 'country')
    op.drop_column('store_addresses', 'state')
    op.drop_column('store_addresses', 'city')
    op.drop_column('store_addresses', 'street')
    # ### end Alembic commands ###
