"""link store table to membership table

Revision ID: 42d7b925d1dc
Revises: 0e4175cba294
Create Date: 2026-04-13 19:11:14.736047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42d7b925d1dc'
down_revision: Union[str, Sequence[str], None] = '0e4175cba294'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memberships', sa.Column('store_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_index(op.f('ix_memberships_store_id'), 'memberships', ['store_id'], unique=False)
    op.create_unique_constraint('user_store_membership', 'memberships', ['user_id', 'store_id'])
    op.create_foreign_key(None, 'memberships', 'stores', ['store_id'], ['id'])
    op.add_column('orders', sa.Column('member_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_orders_member'), table_name='orders')
    op.create_index(op.f('ix_orders_member_id'), 'orders', ['member_id'], unique=False)
    op.drop_constraint(op.f('orders_member_fkey'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'memberships', ['member_id'], ['id'])
    op.drop_column('orders', 'member')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('member', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_member_fkey'), 'orders', 'memberships', ['member'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_orders_member_id'), table_name='orders')
    op.create_index(op.f('ix_orders_member'), 'orders', ['member'], unique=False)
    op.drop_column('orders', 'member_id')
    op.drop_constraint(None, 'memberships', type_='foreignkey')
    op.drop_constraint('user_store_membership', 'memberships', type_='unique')
    op.drop_index(op.f('ix_memberships_store_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=True)
    op.drop_column('memberships', 'store_id')
    # ### end Alembic commands ###
