"""add is_deleted column to inventory table

Revision ID: 432c593224c7
Revises: 96c6dad9713e
Create Date: 2026-04-01 13:01:10.617742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '432c593224c7'
down_revision: Union[str, Sequence[str], None] = '96c6dad9713e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventories', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventories', 'is_deleted')
    # ### end Alembic commands ###
