"""ensure transaction_id can be nullable

Revision ID: 494dac7b91f2
Revises: 8719a521fc70
Create Date: 2026-06-04 23:07:46.993689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '494dac7b91f2'
down_revision: Union[str, Sequence[str], None] = '8719a521fc70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment', 'transaction_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('payment', 'last_event_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment', 'last_event_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('payment', 'transaction_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
