"""add trigram indexes to category and subcategory tables

Revision ID: 4a90952194fb
Revises: 55d6da4e0a6a
Create Date: 2026-08-19 13:46:45.679649

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "4a90952194fb"
down_revision: Union[str, Sequence[str], None] = "55d6da4e0a6a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("category", sa.Column("created_by", sa.Integer(), nullable=True))
    op.add_column(
        "category",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column("category", sa.Column("deleted_by", sa.Integer(), nullable=True))
    op.add_column(
        "category", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_index(
        "idx_category_trgm",
        "category",
        ["name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
        postgresql_where=sa.text("is_deleted IS False"),
    )
    op.alter_column(
        "inventory", "variant_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.add_column("subcategory", sa.Column("created_by", sa.Integer(), nullable=True))
    op.add_column(
        "subcategory",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column("subcategory", sa.Column("deleted_by", sa.Integer(), nullable=True))
    op.add_column(
        "subcategory",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index(
        "idx_subcategory_trgm",
        "subcategory",
        ["name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
        postgresql_where=sa.text("is_deleted IS False"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_subcategory_trgm",
        table_name="subcategory",
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
        postgresql_where=sa.text("is_deleted IS False"),
    )
    op.drop_column("subcategory", "deleted_at")
    op.drop_column("subcategory", "deleted_by")
    op.drop_column("subcategory", "created_at")
    op.drop_column("subcategory", "created_by")
    op.alter_column(
        "inventory", "variant_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_index(
        "idx_category_trgm",
        table_name="category",
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
        postgresql_where=sa.text("is_deleted IS False"),
    )
    op.drop_column("category", "deleted_at")
    op.drop_column("category", "deleted_by")
    op.drop_column("category", "created_at")
    op.drop_column("category", "created_by")
    # ### end Alembic commands ###
