"""add Notification table

Revision ID: 4f1fae2d0aa7
Revises: 9e1b4063a1d2
Create Date: 2026-05-03 17:01:15.518126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f1fae2d0aa7'
down_revision: Union[str, Sequence[str], None] = '9e1b4063a1d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification', sa.String(), nullable=False),
    sa.Column('notified_user', sa.Integer(), nullable=False),
    sa.Column('time_of_op', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_notified_user'), 'notifications', ['notified_user'], unique=False)
    op.add_column('reviews', sa.Column('time_of_post', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_index(op.f('ix_reviews_date_of_review'), table_name='reviews')
    op.create_index(op.f('ix_reviews_time_of_post'), 'reviews', ['time_of_post'], unique=False)
    op.drop_column('reviews', 'date_of_review')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('date_of_review', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_reviews_time_of_post'), table_name='reviews')
    op.create_index(op.f('ix_reviews_date_of_review'), 'reviews', ['date_of_review'], unique=False)
    op.drop_column('reviews', 'time_of_post')
    op.drop_index(op.f('ix_notifications_notified_user'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
