"""add nullable = false for delivery address column in order table

Revision ID: 5263f7f238df
Revises: f86c4b895392
Create Date: 2026-05-28 19:56:03.202816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5263f7f238df'
down_revision: Union[str, Sequence[str], None] = 'f86c4b895392'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orderitem', sa.Column('product_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_orderitem_product_id'), 'orderitem', ['product_id'], unique=False)
    op.drop_constraint(op.f('orderitem_order_id_fkey'), 'orderitem', type_='foreignkey')
    op.drop_constraint(op.f('orderitem_cartitem_id_fkey'), 'orderitem', type_='foreignkey')
    op.create_foreign_key(None, 'orderitem', 'product', ['product_id'], ['id'])
    op.create_foreign_key(None, 'orderitem', 'cartitem', ['cartitem_id'], ['id'])
    op.create_foreign_key(None, 'orderitem', 'order', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orderitem', type_='foreignkey')
    op.drop_constraint(None, 'orderitem', type_='foreignkey')
    op.drop_constraint(None, 'orderitem', type_='foreignkey')
    op.create_foreign_key(op.f('orderitem_cartitem_id_fkey'), 'orderitem', 'cartitem', ['cartitem_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('orderitem_order_id_fkey'), 'orderitem', 'order', ['order_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_orderitem_product_id'), table_name='orderitem')
    op.drop_column('orderitem', 'product_id')
    # ### end Alembic commands ###
