"""drop unique constraint

Revision ID: 53da0f54f18e
Revises: fcc7c242667f
Create Date: 2026-07-15 16:27:07.012802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53da0f54f18e'
down_revision: Union[str, Sequence[str], None] = 'fcc7c242667f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_store_review'), 'review', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('user_store_review'), 'review', ['user_id', 'store_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
