"""add address fk to order table

Revision ID: 5461c335ac92
Revises: 268d631fdf32
Create Date: 2026-04-06 15:57:33.554763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5461c335ac92'
down_revision: Union[str, Sequence[str], None] = '268d631fdf32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('street', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_is_deleted'), 'addresses', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_addresses_store_id'), 'addresses', ['store_id'], unique=False)
    op.drop_index(op.f('ix_store_addresses_is_deleted'), table_name='store_addresses')
    op.drop_index(op.f('ix_store_addresses_store_id'), table_name='store_addresses')
    op.drop_table('store_addresses')
    op.add_column('orders', sa.Column('delivery_address_id', sa.Integer(), nullable=False))
    op.add_column('orders', sa.Column('delivery_address', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.alter_column('orders', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('orders', 'store_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('orders', 'member',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('orders', 'total_quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('orders', 'order_delete',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('orders', 'total_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_index(op.f('ix_orders_delivery_address_id'), 'orders', ['delivery_address_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'addresses', ['delivery_address_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_delivery_address_id'), table_name='orders')
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('orders', 'total_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('orders', 'order_delete',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('orders', 'total_quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('orders', 'member',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('orders', 'store_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('orders', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('orders', 'delivery_address')
    op.drop_column('orders', 'delivery_address_id')
    op.create_table('store_addresses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('street', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('store_addresses_store_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('store_addresses_pkey'))
    )
    op.create_index(op.f('ix_store_addresses_store_id'), 'store_addresses', ['store_id'], unique=False)
    op.create_index(op.f('ix_store_addresses_is_deleted'), 'store_addresses', ['is_deleted'], unique=False)
    op.drop_index(op.f('ix_addresses_store_id'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_is_deleted'), table_name='addresses')
    op.drop_table('addresses')
    # ### end Alembic commands ###
