"""add weighted tsvector computed column

Revision ID: 55d6da4e0a6a
Revises: 0f6a13f89755
Create Date: 2026-08-19 13:02:57.599370

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "55d6da4e0a6a"
down_revision: Union[str, Sequence[str], None] = "0f6a13f89755"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("idx_category_pg_trgm"),
        table_name="category",
        postgresql_ops={"name": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.alter_column(
        "inventory", "variant_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.add_column(
        "product",
        sa.Column(
            "searchable_text",
            postgresql.TSVECTOR(),
            sa.Computed(
                "setweight(to_tsvector('english', coalesce(product_name, '')), 'A') || setweight(to_tsvector('english', coalesce(product_description, '')), 'B')",
                persisted=True,
            ),
            nullable=False,
        ),
    )
    op.drop_index(
        op.f("idx_gin_search_vector"), table_name="product", postgresql_using="gin"
    )
    op.create_index(
        "idx_gin_searchable_text",
        "product",
        ["searchable_text"],
        unique=False,
        postgresql_using="gin",
    )
    op.drop_column("product", "search_vector")
    op.drop_index(
        op.f("idx_sub_category_pg_trgm"),
        table_name="subcategory",
        postgresql_ops={"name": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("idx_sub_category_pg_trgm"),
        "subcategory",
        ["name"],
        unique=False,
        postgresql_ops={"name": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.add_column(
        "product",
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed(
                "to_tsvector('english'::regconfig, (product_name)::text)",
                persisted=True,
            ),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_index(
        "idx_gin_searchable_text", table_name="product", postgresql_using="gin"
    )
    op.create_index(
        op.f("idx_gin_search_vector"),
        "product",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.drop_column("product", "searchable_text")
    op.alter_column(
        "inventory", "variant_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.create_index(
        op.f("idx_category_pg_trgm"),
        "category",
        ["name"],
        unique=False,
        postgresql_ops={"name": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    # ### end Alembic commands ###
