"""add from_user column to notifications table

Revision ID: 569575ba3d2c
Revises: 2ef2d68f3dab
Create Date: 2026-05-23 20:14:12.864882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '569575ba3d2c'
down_revision: Union[str, Sequence[str], None] = '2ef2d68f3dab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('from_user', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_notifications_notified_user'), table_name='notifications')
    op.create_index(op.f('ix_notifications_from_user'), 'notifications', ['from_user'], unique=False)
    op.drop_column('notifications', 'notified_user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('notified_user', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_notifications_from_user'), table_name='notifications')
    op.create_index(op.f('ix_notifications_notified_user'), 'notifications', ['notified_user'], unique=False)
    op.drop_column('notifications', 'from_user')
    # ### end Alembic commands ###
