"""delete pause and pause_date columns from membership table

Revision ID: 5a630ac4adce
Revises: e66ccf297b11
Create Date: 2026-06-24 17:15:46.826821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a630ac4adce'
down_revision: Union[str, Sequence[str], None] = 'e66ccf297b11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_membership_is_pause'), table_name='membership')
    op.drop_column('membership', 'pause_date')
    op.drop_column('membership', 'is_pause')
    op.create_unique_constraint('subscribed_member', 'subscription', ['membership_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('subscribed_member', 'subscription', type_='unique')
    op.add_column('membership', sa.Column('is_pause', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('membership', sa.Column('pause_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_membership_is_pause'), 'membership', ['is_pause'], unique=False)
    # ### end Alembic commands ###
