"""add check_out and check_out_time columns to order table

Revision ID: 5e2934133d66
Revises: e0cdc0ce3851
Create Date: 2026-04-16 19:30:26.350066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e2934133d66'
down_revision: Union[str, Sequence[str], None] = 'e0cdc0ce3851'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orderitems', sa.Column('cartitem_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_orderitems_cart_items'), table_name='orderitems')
    op.create_index(op.f('ix_orderitems_cartitem_id'), 'orderitems', ['cartitem_id'], unique=False)
    op.drop_constraint(op.f('orderitems_cart_items_fkey'), 'orderitems', type_='foreignkey')
    op.create_foreign_key(None, 'orderitems', 'cartitems', ['cartitem_id'], ['id'], ondelete='CASCADE')
    op.drop_column('orderitems', 'cart_items')
    op.add_column('orders', sa.Column('check_out', sa.Boolean(), nullable=False))
    op.add_column('orders', sa.Column('check_out_time', sa.DateTime(timezone=True), nullable=False))
    op.create_index(op.f('ix_orders_check_out_time'), 'orders', ['check_out_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_check_out_time'), table_name='orders')
    op.drop_column('orders', 'check_out_time')
    op.drop_column('orders', 'check_out')
    op.add_column('orderitems', sa.Column('cart_items', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orderitems', type_='foreignkey')
    op.create_foreign_key(op.f('orderitems_cart_items_fkey'), 'orderitems', 'cartitems', ['cart_items'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_orderitems_cartitem_id'), table_name='orderitems')
    op.create_index(op.f('ix_orderitems_cart_items'), 'orderitems', ['cart_items'], unique=False)
    op.drop_column('orderitems', 'cartitem_id')
    # ### end Alembic commands ###
