"""status column in order table not nullable

Revision ID: 60ad5e7c2a02
Revises: ef519e58fc68
Create Date: 2026-04-04 18:33:19.437278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '60ad5e7c2a02'
down_revision: Union[str, Sequence[str], None] = 'ef519e58fc68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'status',
               existing_type=postgresql.ENUM('pending', 'processing', 'shipped', 'delivered', 'cancelled', name='orderstatus'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'status',
               existing_type=postgresql.ENUM('pending', 'processing', 'shipped', 'delivered', 'cancelled', name='orderstatus'),
               nullable=True)
    # ### end Alembic commands ###
