"""add check constraint to user table

Revision ID: 61deb12fe0af
Revises: 0a12c257a48e
Create Date: 2026-08-01 13:10:13.862635

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "61deb12fe0af"
down_revision: Union[str, Sequence[str], None] = "0a12c257a48e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        "ck_user_ban_state_integrity_v2",
        "user",
        """
               (
                   -- State 1: Temp Ban -> MUST have reason, date, period, unit
                   is_banned = TRUE 
                   AND indefinite_ban = FALSE 
                   AND ban_reason IS NOT NULL 
                   AND ban_date IS NOT NULL
                   AND ban_period != 0 
                   AND ban_unit IS NOT NULL 
               ) 
               OR 
               (
                   -- State 2: Indefinite Ban -> MUST have reason & date, MUST NOT have period/unit
                   is_banned = TRUE 
                   AND indefinite_ban = TRUE 
                   AND ban_reason IS NOT NULL 
                   AND ban_date IS NOT NULL 
                   AND ban_period = 0
                   AND ban_unit IS NULL
               ) 
               OR 
               (
                   -- State 3: Unbanned -> MUST NOT have lingering ban_unit
                   is_banned = FALSE 
                   AND indefinite_ban = FALSE 
                   AND ban_unit IS NULL
               )
               """,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
