"""add nullable to founded column

Revision ID: 61f2e58a30fa
Revises: d8937728c84a
Create Date: 2026-05-06 14:30:02.814634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61f2e58a30fa'
down_revision: Union[str, Sequence[str], None] = 'd8937728c84a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stores', 'motto',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('stores', 'store_previous_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('stores', 'store_description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('stores', 'founded',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stores', 'founded',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('stores', 'store_description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('stores', 'store_previous_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('stores', 'motto',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
