"""add index to fk

Revision ID: 62762d730102
Revises: ee0c6724434e
Create Date: 2026-03-26 20:14:29.187124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62762d730102'
down_revision: Union[str, Sequence[str], None] = 'ee0c6724434e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_carts_member_id'), 'carts', ['member_id'], unique=False)
    op.create_index(op.f('ix_store_addresses_store_id'), 'store_addresses', ['store_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_store_addresses_store_id'), table_name='store_addresses')
    op.drop_index(op.f('ix_carts_member_id'), table_name='carts')
    # ### end Alembic commands ###
