"""add checkout_url column to payment table

Revision ID: 62aaf624f9f2
Revises: 494dac7b91f2
Create Date: 2026-06-05 11:39:26.527632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62aaf624f9f2'
down_revision: Union[str, Sequence[str], None] = '494dac7b91f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_order_paymennt', 'payment', ['order_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_order_paymennt', 'payment', type_='unique')
    # ### end Alembic commands ###
