"""change account_name to  account_holder_name

Revision ID: 67199ebb0d71
Revises: 0f2186d10fea
Create Date: 2026-05-14 18:09:39.930542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67199ebb0d71'
down_revision: Union[str, Sequence[str], None] = '0f2186d10fea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_accounts', sa.Column('account_holder_name', sa.String(), nullable=False))
    op.drop_column('store_accounts', 'account_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_accounts', sa.Column('account_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('store_accounts', 'account_holder_name')
    # ### end Alembic commands ###
