"""change description to product_description

Revision ID: 7077e7b3ab5d
Revises: a776f2b53234
Create Date: 2026-05-18 17:39:46.780561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7077e7b3ab5d'
down_revision: Union[str, Sequence[str], None] = 'a776f2b53234'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_description', sa.String(), nullable=False))
    op.drop_column('products', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('products', 'product_description')
    # ### end Alembic commands ###
