"""fix typo

Revision ID: 720b25063727
Revises: 151c303554e8
Create Date: 2026-04-27 14:02:47.470158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '720b25063727'
down_revision: Union[str, Sequence[str], None] = '151c303554e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('sub_category_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_products_subcategory_id'), table_name='products')
    op.create_index(op.f('ix_products_sub_category_id'), 'products', ['sub_category_id'], unique=False)
    op.drop_constraint(op.f('products_subcategory_id_fkey'), 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'subcategories', ['sub_category_id'], ['id'])
    op.drop_column('products', 'subcategory_id')
    op.add_column('stores', sa.Column('sub_category_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_stores_subcategory_id'), table_name='stores')
    op.create_index(op.f('ix_stores_sub_category_id'), 'stores', ['sub_category_id'], unique=False)
    op.drop_constraint(op.f('stores_subcategory_id_fkey'), 'stores', type_='foreignkey')
    op.create_foreign_key(None, 'stores', 'subcategories', ['sub_category_id'], ['id'])
    op.drop_column('stores', 'subcategory_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('subcategory_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'stores', type_='foreignkey')
    op.create_foreign_key(op.f('stores_subcategory_id_fkey'), 'stores', 'subcategories', ['subcategory_id'], ['id'])
    op.drop_index(op.f('ix_stores_sub_category_id'), table_name='stores')
    op.create_index(op.f('ix_stores_subcategory_id'), 'stores', ['subcategory_id'], unique=False)
    op.drop_column('stores', 'sub_category_id')
    op.add_column('products', sa.Column('subcategory_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(op.f('products_subcategory_id_fkey'), 'products', 'subcategories', ['subcategory_id'], ['id'])
    op.drop_index(op.f('ix_products_sub_category_id'), table_name='products')
    op.create_index(op.f('ix_products_subcategory_id'), 'products', ['subcategory_id'], unique=False)
    op.drop_column('products', 'sub_category_id')
    # ### end Alembic commands ###
