"""add shipping fee column to order table

Revision ID: 77297b60b57e
Revises: fb642ea1fc89
Create Date: 2026-04-08 17:45:58.339102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77297b60b57e'
down_revision: Union[str, Sequence[str], None] = 'fb642ea1fc89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('orders', sa.Column('shipping_fee', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('orders', sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('orders', sa.Column('refference_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_orders_refference_id'), 'orders', ['refference_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_refference_id'), table_name='orders')
    op.drop_column('orders', 'refference_id')
    op.drop_column('orders', 'discount_amount')
    op.drop_column('orders', 'shipping_fee')
    op.drop_column('orders', 'tax_amount')
    # ### end Alembic commands ###
