"""add enum table for business type column in store table

Revision ID: 77bda13a3bb0
Revises: ce64a73435a4
Create Date: 2026-03-19 19:18:55.255852

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "77bda13a3bb0"
down_revision: Union[str, Sequence[str], None] = "ce64a73435a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.dialects import postgresql

    business_type_enum = postgresql.ENUM(
        "beauty_and_hair",
        "skincare",
        "hair",
        "electronics",
        "fashion",
        "kitchen_wares",
        "groceries",
        "fruits_and_vegetables",
        "footwear",
        "bags",
        "luggages",
        "games",
        "computers",
        name="businesstype",
    )
    business_type_enum.create(op.get_bind())
    op.create_table(
        "store_addresses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("store_id", sa.Integer(), nullable=False),
        sa.Column("address", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("replies", sa.Column("product_id", sa.Integer(), nullable=True))
    op.add_column("replies", sa.Column("store_id", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_replies_product_id"), "replies", ["product_id"], unique=False
    )
    op.create_index(op.f("ix_replies_store_id"), "replies", ["store_id"], unique=False)
    op.create_foreign_key(None, "replies", "stores", ["store_id"], ["id"])
    op.create_foreign_key(None, "replies", "products", ["product_id"], ["id"])
    op.add_column("stores", sa.Column("store_email", sa.String(), nullable=True))
    op.add_column("stores", sa.Column("store_contact", sa.String(), nullable=True))
    op.alter_column(
        "stores",
        "business_type",
        existing_type=sa.VARCHAR(),
        type_=sa.Enum(
            "beauty_and_hair",
            "skincare",
            "hair",
            "electronics",
            "fashion",
            "kitchen_wares",
            "groceries",
            "fruits_and_vegetables",
            "footwear",
            "bags",
            "luggages",
            "games",
            "computers",
            name="businesstype",
        ),
        existing_nullable=False,
        postgresql_using="business_type::businesstype",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "stores",
        "business_type",
        existing_type=sa.Enum(
            "beauty_and_hair",
            "skincare",
            "hair",
            "electronics",
            "fashion",
            "kitchen_wares",
            "groceries",
            "fruits_and_vegetables",
            "footwear",
            "bags",
            "luggages",
            "games",
            "computers",
            name="businesstype",
        ),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.drop_column("stores", "store_contact")
    op.drop_column("stores", "store_email")
    op.drop_constraint(None, "replies", type_="foreignkey")
    op.drop_constraint(None, "replies", type_="foreignkey")
    op.drop_index(op.f("ix_replies_store_id"), table_name="replies")
    op.drop_index(op.f("ix_replies_product_id"), table_name="replies")
    op.drop_column("replies", "store_id")
    op.drop_column("replies", "product_id")
    op.drop_table("store_addresses")
    op.execute("DROP TYPE businesstype")
    # ### end Alembic commands ###
