"""add notified_user column to notifications table

Revision ID: 7917abc87191
Revises: 569575ba3d2c
Create Date: 2026-05-23 20:22:18.995779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7917abc87191'
down_revision: Union[str, Sequence[str], None] = '569575ba3d2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('notified_user', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_notifications_notified_user'), 'notifications', ['notified_user'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_notified_user'), table_name='notifications')
    op.drop_column('notifications', 'notified_user')
    # ### end Alembic commands ###
