"""add subtotal column to order table

Revision ID: 81c68553bfca
Revises: ab3a512af6d4
Create Date: 2026-05-31 19:05:13.768341

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "81c68553bfca"
down_revision: Union[str, Sequence[str], None] = "ab3a512af6d4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order", sa.Column("subtotal", sa.Numeric(precision=12, scale=2), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order", "subtotal")
    # ### end Alembic commands ###
