"""add unique constraint to reply table

Revision ID: 81d4104a82ca
Revises: a4800bba6557
Create Date: 2026-07-02 19:35:30.952099

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "81d4104a82ca"
down_revision: Union[str, Sequence[str], None] = "a4800bba6557"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("unique_reply"), "reply", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_reply", "reply", type_="unique")
    op.create_unique_constraint(
        op.f("unique_reply"),
        "reply",
        ["review_id"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
