"""add product_type column to product table

Revision ID: 869e9818a237
Revises: 2c331b23f31f
Create Date: 2026-04-20 17:12:43.629086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '869e9818a237'
down_revision: Union[str, Sequence[str], None] = '2c331b23f31f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_type', sa.String(), nullable=False))
    op.add_column('products', sa.Column('description', sa.String(), nullable=True))
    op.drop_column('products', 'product_description')
    op.add_column('refunds', sa.Column('refund_amount', sa.Numeric(precision=10, scale=2), nullable=False))
    op.drop_column('refunds', 'amount_refunded')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refunds', sa.Column('amount_refunded', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_column('refunds', 'refund_amount')
    op.add_column('products', sa.Column('product_description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('products', 'description')
    op.drop_column('products', 'product_type')
    # ### end Alembic commands ###
