"""added column to reviews table

Revision ID: 871793f81498
Revises: 5d140bd3e325
Create Date: 2025-12-29 16:26:55.601935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '871793f81498'
down_revision: Union[str, Sequence[str], None] = '5d140bd3e325'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cartitems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cartitems_id'), 'cartitems', ['id'], unique=False)
    op.add_column('carts', sa.Column('member', sa.Integer(), nullable=True))
    op.add_column('carts', sa.Column('total_quantity', sa.Float(), nullable=True))
    op.add_column('carts', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('carts_product_id_fkey'), 'carts', type_='foreignkey')
    op.create_foreign_key(None, 'carts', 'memberships', ['member'], ['id'], ondelete='CASCADE')
    op.drop_column('carts', 'product_id')
    op.drop_column('carts', 'quantity')
    op.add_column('memberships', sa.Column('offers', sa.String(), nullable=True))
    op.add_column('memberships', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('memberships', sa.Column('pause_date', sa.Date(), nullable=True))
    op.add_column('memberships', sa.Column('reactivation_date', sa.Date(), nullable=True))
    op.alter_column('memberships', 'period_of_membership',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('memberships', 'start_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Date(),
               existing_nullable=True)
    op.drop_column('memberships', 'address')
    op.add_column('orderitems', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('orderitems', 'quantity',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_constraint(op.f('orderitems_order_id_fkey'), 'orderitems', type_='foreignkey')
    op.create_foreign_key(None, 'orderitems', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'orderitems', 'users', ['user_id'], ['id'])
    op.add_column('orders', sa.Column('member', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('total_quantity', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'orders', 'memberships', ['member'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('replies_review_id_fkey'), 'replies', type_='foreignkey')
    op.create_foreign_key(None, 'replies', 'reviews', ['review_id'], ['id'], ondelete='CASCADE')
    op.add_column('reviews', sa.Column('product_name', sa.String(), nullable=True))
    op.add_column('reviews', sa.Column('edited', sa.Boolean(), nullable=True))
    op.drop_constraint(op.f('reviews_product_id_fkey'), 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('reviews_product_id_fkey'), 'reviews', 'products', ['product_id'], ['id'])
    op.drop_column('reviews', 'edited')
    op.drop_column('reviews', 'product_name')
    op.drop_constraint(None, 'replies', type_='foreignkey')
    op.create_foreign_key(op.f('replies_review_id_fkey'), 'replies', 'reviews', ['review_id'], ['id'])
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'total_quantity')
    op.drop_column('orders', 'member')
    op.drop_constraint(None, 'orderitems', type_='foreignkey')
    op.drop_constraint(None, 'orderitems', type_='foreignkey')
    op.create_foreign_key(op.f('orderitems_order_id_fkey'), 'orderitems', 'orders', ['order_id'], ['id'])
    op.alter_column('orderitems', 'quantity',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('orderitems', 'user_id')
    op.add_column('memberships', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('memberships', 'start_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('memberships', 'period_of_membership',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_column('memberships', 'reactivation_date')
    op.drop_column('memberships', 'pause_date')
    op.drop_column('memberships', 'is_active')
    op.drop_column('memberships', 'offers')
    op.add_column('carts', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('carts', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'carts', type_='foreignkey')
    op.create_foreign_key(op.f('carts_product_id_fkey'), 'carts', 'products', ['product_id'], ['id'])
    op.drop_column('carts', 'created_at')
    op.drop_column('carts', 'total_quantity')
    op.drop_column('carts', 'member')
    op.drop_index(op.f('ix_cartitems_id'), table_name='cartitems')
    op.drop_table('cartitems')
    # ### end Alembic commands ###
