"""add currency column to payment table

Revision ID: 8719a521fc70
Revises: 1991198f7ad7
Create Date: 2026-06-04 22:54:59.426434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8719a521fc70'
down_revision: Union[str, Sequence[str], None] = '1991198f7ad7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('currency', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'currency')
    # ### end Alembic commands ###
