"""add product_review_count and store_review_count to review table

Revision ID: 8872b742d9b4
Revises: be53d7e7346a
Create Date: 2026-06-26 21:36:09.435576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8872b742d9b4'
down_revision: Union[str, Sequence[str], None] = 'be53d7e7346a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('product_review_count', sa.Integer(), nullable=False))
    op.add_column('review', sa.Column('store_review_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'store_review_count')
    op.drop_column('review', 'product_review_count')
    # ### end Alembic commands ###
