"""move stock quantity from product table to inventory table

Revision ID: 904c47f037d2
Revises: aea87eb97134
Create Date: 2026-04-03 17:23:23.598006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '904c47f037d2'
down_revision: Union[str, Sequence[str], None] = 'aea87eb97134'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventories', sa.Column('stock_quantity', sa.Integer(), nullable=False))
    op.drop_column('inventories', 'quantity')
    op.drop_column('products', 'stock_quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('stock_quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('inventories', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('inventories', 'stock_quantity')
    # ### end Alembic commands ###
