"""remove description column from ticket table

Revision ID: 90ae0ea04506
Revises: 81d4104a82ca
Create Date: 2026-07-06 16:05:16.329804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90ae0ea04506'
down_revision: Union[str, Sequence[str], None] = '81d4104a82ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
