"""add product_id and store_id columns to notification table

Revision ID: 9342bbf119b6
Revises: a1166ae371d0
Create Date: 2026-07-15 10:45:31.427128

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "9342bbf119b6"
down_revision: Union[str, Sequence[str], None] = "a1166ae371d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("notification", sa.Column("product_id", sa.Integer(), nullable=True))
    op.add_column("notification", sa.Column("store_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("notification", "store_id")
    op.drop_column("notification", "product_id")
    # ### end Alembic commands ###
