"""add category column to store table

Revision ID: 98c02902bd43
Revises: 4f1fae2d0aa7
Create Date: 2026-05-04 18:12:05.297857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98c02902bd43'
down_revision: Union[str, Sequence[str], None] = '4f1fae2d0aa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stores_business_type'), table_name='stores')
    op.drop_index(op.f('ix_stores_store_previous_name'), table_name='stores')
    op.drop_column('stores', 'business_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('business_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_stores_store_previous_name'), 'stores', ['store_previous_name'], unique=False)
    op.create_index(op.f('ix_stores_business_type'), 'stores', ['business_type'], unique=False)
    # ### end Alembic commands ###
