"""add last event id column

Revision ID: 9ddf568c5467
Revises: 4262bad5abba
Create Date: 2026-04-12 20:22:20.667884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ddf568c5467'
down_revision: Union[str, Sequence[str], None] = '4262bad5abba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('last_event_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_payments_last_event_id'), 'payments', ['last_event_id'], unique=False)
    op.add_column('subscriptions', sa.Column('plan_price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('subscriptions', sa.Column('status', sa.String(), nullable=False))
    op.add_column('subscriptions', sa.Column('customer_id', sa.String(), nullable=False))
    op.add_column('subscriptions', sa.Column('reference_id', sa.String(), nullable=False))
    op.add_column('subscriptions', sa.Column('last_event_id', sa.String(), nullable=False))
    op.drop_index(op.f('ix_subscriptions_plan_name'), table_name='subscriptions')
    op.create_index(op.f('ix_subscriptions_plan_name'), 'subscriptions', ['plan_name'], unique=False)
    op.create_index(op.f('ix_subscriptions_expire_at'), 'subscriptions', ['expire_at'], unique=False)
    op.create_index(op.f('ix_subscriptions_last_event_id'), 'subscriptions', ['last_event_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_reference_id'), 'subscriptions', ['reference_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.drop_column('subscriptions', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_reference_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_last_event_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_expire_at'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_plan_name'), table_name='subscriptions')
    op.create_index(op.f('ix_subscriptions_plan_name'), 'subscriptions', ['plan_name'], unique=True)
    op.drop_column('subscriptions', 'last_event_id')
    op.drop_column('subscriptions', 'reference_id')
    op.drop_column('subscriptions', 'customer_id')
    op.drop_column('subscriptions', 'status')
    op.drop_column('subscriptions', 'plan_price')
    op.drop_index(op.f('ix_payments_last_event_id'), table_name='payments')
    op.drop_column('payments', 'last_event_id')
    # ### end Alembic commands ###
