"""add phone_number column in user table

Revision ID: 9e1b4063a1d2
Revises: f9aa720f7021
Create Date: 2026-04-29 14:04:49.938073

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "9e1b4063a1d2"
down_revision: Union[str, Sequence[str], None] = "f9aa720f7021"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "store_accounts",
        "account_name",
        existing_type=sa.VARCHAR(),
        type_=sa.LargeBinary(),
        existing_nullable=False,
        postgresql_using="account_name::bytea",
    )
    op.add_column("users", sa.Column("phone_number", sa.String(), nullable=True))
    op.alter_column("users", "first_name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("users", "surname", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("users", "username", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("users", "password", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("users", "is_active", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("users", "role", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("users", "email", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("users", "nationality", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "nationality", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "email", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "role", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "is_active", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("users", "password", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "username", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "surname", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "first_name", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("users", "phone_number")
    op.alter_column(
        "store_accounts",
        "account_name",
        existing_type=sa.LargeBinary(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
