"""add store_ticket relationship

Revision ID: a1166ae371d0
Revises: 90ae0ea04506
Create Date: 2026-07-08 10:29:55.175371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1166ae371d0'
down_revision: Union[str, Sequence[str], None] = '90ae0ea04506'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('message', 'ticket_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('message', 'support_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('message', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('message', 'delivered',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('message', 'seen',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('message', 'sender_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('message', 'receiver_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('message', 'time_of_chat',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('ticket', sa.Column('store_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ticket', 'store', ['store_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ticket', type_='foreignkey')
    op.drop_column('ticket', 'store_id')
    op.alter_column('message', 'time_of_chat',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('message', 'receiver_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('message', 'sender_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('message', 'seen',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('message', 'delivered',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('message', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('message', 'support_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('message', 'ticket_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('message', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
