"""add SubscriptionStatus enum

Revision ID: a2554765a2ff
Revises: 03fcd6b727fe
Create Date: 2026-06-10 14:19:13.210550

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import postgresql
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "a2554765a2ff"
down_revision: Union[str, Sequence[str], None] = "03fcd6b727fe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    substatus = postgresql.ENUM(
        "inactive", "active", "past_due", "cancelled", name="subscriptionstatus"
    )
    substatus.create(op.get_bind(), checkfirst=True)
    op.alter_column(
        "subscription",
        "status",
        existing_type=sa.VARCHAR(),
        type_=sa.Enum(
            "inactive", "active", "past_due", "cancelled", name="subscriptionstatus"
        ),
        postgresql_using="status::subscriptionstatus",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "subscription",
        "status",
        existing_type=sa.Enum(
            "inactive", "active", "past_due", "cancelled", name="subscriptionstatus"
        ),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
