"""add unique constraint to reply table

Revision ID: a4800bba6557
Revises: 7a2fd6b06d75
Create Date: 2026-06-30 15:11:02.564039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4800bba6557'
down_revision: Union[str, Sequence[str], None] = '7a2fd6b06d75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_reply', 'reply', ['review_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_reply', 'reply', type_='unique')
    # ### end Alembic commands ###
