"""add FK for store and product in product image table

Revision ID: a776f2b53234
Revises: e04052581945
Create Date: 2026-05-18 17:24:42.168519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a776f2b53234'
down_revision: Union[str, Sequence[str], None] = 'e04052581945'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'product_images', 'products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'product_images', 'stores', ['store_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_images', type_='foreignkey')
    op.drop_constraint(None, 'product_images', type_='foreignkey')
    # ### end Alembic commands ###
