"""add tax_rate column to payment, order and store table

Revision ID: ab3a512af6d4
Revises: c1bcc40c9f58
Create Date: 2026-05-31 18:43:55.325419

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "ab3a512af6d4"
down_revision: Union[str, Sequence[str], None] = "c1bcc40c9f58"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("order", sa.Column("tax_rate", sa.Float(), nullable=True))
    op.drop_column("order", "tax_amount")
    op.add_column("payment", sa.Column("tax_rate", sa.Float(), nullable=True))
    op.drop_column("payment", "tax_amount")
    op.add_column("store", sa.Column("tax_rate", sa.Float(), nullable=True))
    op.drop_column("store", "tax_amount")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "store",
        sa.Column(
            "tax_amount",
            sa.NUMERIC(precision=10, scale=2),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("store", "tax_rate")
    op.add_column(
        "payment",
        sa.Column(
            "tax_amount",
            sa.NUMERIC(precision=10, scale=2),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("payment", "tax_rate")
    op.add_column(
        "order",
        sa.Column(
            "tax_amount",
            sa.NUMERIC(precision=12, scale=2),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("order", "tax_rate")
    # ### end Alembic commands ###
