"""add last_event_at column to payment table

Revision ID: aceebce05bd4
Revises: 895b26467b9d
Create Date: 2026-06-05 19:01:59.688288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aceebce05bd4'
down_revision: Union[str, Sequence[str], None] = '895b26467b9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('last_event_at', sa.DateTime(timezone=True), nullable=False))
    op.create_index(op.f('ix_payment_last_event_at'), 'payment', ['last_event_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_last_event_at'), table_name='payment')
    op.drop_column('payment', 'last_event_at')
    # ### end Alembic commands ###
