"""add is deleted column to address table

Revision ID: aea87eb97134
Revises: 432c593224c7
Create Date: 2026-04-01 18:33:56.104833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aea87eb97134'
down_revision: Union[str, Sequence[str], None] = '432c593224c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_addresses', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_store_addresses_is_deleted'), 'store_addresses', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_store_addresses_is_deleted'), table_name='store_addresses')
    op.drop_column('store_addresses', 'is_deleted')
    # ### end Alembic commands ###
