"""add composite index to message table

Revision ID: b1c3ab7378fa
Revises: 61deb12fe0af
Create Date: 2026-08-03 20:49:10.783476

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "b1c3ab7378fa"
down_revision: Union[str, Sequence[str], None] = "61deb12fe0af"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_message_customer_support",
        "message",
        ["customer_id", "support_id", "time_of_chat"],
        unique=False,
    )
    op.create_index(
        "idx_message_ticket_time",
        "message",
        ["ticket_id", "time_of_chat"],
        unique=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_message_ticket_time", table_name="message")
    op.drop_index("idx_message_customer_support", table_name="message")
    # ### end Alembic commands ###
