"""add gin index to sub_category column in store table

Revision ID: b5cda347cda9
Revises: 4a90952194fb
Create Date: 2026-08-19 18:58:46.165170

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b5cda347cda9"
down_revision: Union[str, Sequence[str], None] = "4a90952194fb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "category", "created_by", existing_type=sa.INTEGER(), nullable=False
    )
    op.add_column(
        "store",
        sa.Column(
            "searchable_text",
            postgresql.TSVECTOR(),
            sa.Computed(
                "setweight(to_tsvector('english', coalesce(store_name, '')), 'A') || setweight(to_tsvector('english', coalesce(sub_category::text, '')), 'B') || setweight(to_tsvector('english', coalesce(category_name, '')), 'C')",
                persisted=True,
            ),
            nullable=False,
        ),
    )
    op.add_column("store", sa.Column("updated_by", sa.Integer(), nullable=True))
    op.add_column(
        "store",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column("store", sa.Column("deleted_by", sa.Integer(), nullable=True))
    op.add_column(
        "store", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.drop_index(op.f("ix_store_is_deleted"), table_name="store")
    op.drop_index(op.f("ix_store_sub_category"), table_name="store")
    op.create_index(
        "idx_searchable_text_ts",
        "store",
        ["searchable_text"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"sub_category": "jsonb_path_ops"},
    )
    op.create_index(
        "idx_sub_category_gin",
        "store",
        ["sub_category"],
        unique=False,
        postgresql_using="gin",
    )
    op.alter_column(
        "subcategory", "created_by", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "subcategory", "created_by", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_index("idx_sub_category_gin", table_name="store", postgresql_using="gin")
    op.drop_index(
        "idx_searchable_text_ts",
        table_name="store",
        postgresql_using="gin",
        postgresql_ops={"sub_category": "jsonb_path_ops"},
    )
    op.create_index(
        op.f("ix_store_sub_category"), "store", ["sub_category"], unique=False
    )
    op.create_index(op.f("ix_store_is_deleted"), "store", ["is_deleted"], unique=False)
    op.drop_column("store", "deleted_at")
    op.drop_column("store", "deleted_by")
    op.drop_column("store", "updated_at")
    op.drop_column("store", "updated_by")
    op.drop_column("store", "created_by")
    op.drop_column("store", "searchable_text")
    op.alter_column("category", "created_by", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
