"""drop product_review_count and store_review_count columns

Revision ID: b7a3f2a6179c
Revises: 8872b742d9b4
Create Date: 2026-06-27 13:48:11.856655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7a3f2a6179c'
down_revision: Union[str, Sequence[str], None] = '8872b742d9b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'store_review_count')
    op.drop_column('review', 'product_review_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('product_review_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('review', sa.Column('store_review_count', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
