"""drop cartitem and orderitem relationship

Revision ID: be53d7e7346a
Revises: a0b729ce324e
Create Date: 2026-06-26 17:01:58.445168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be53d7e7346a'
down_revision: Union[str, Sequence[str], None] = 'a0b729ce324e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orderitem_cartitem_id'), table_name='orderitem')
    op.drop_constraint(op.f('orderitem_cartitem_id_fkey'), 'orderitem', type_='foreignkey')
    op.drop_column('orderitem', 'cartitem_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orderitem', sa.Column('cartitem_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('orderitem_cartitem_id_fkey'), 'orderitem', 'cartitem', ['cartitem_id'], ['id'])
    op.create_index(op.f('ix_orderitem_cartitem_id'), 'orderitem', ['cartitem_id'], unique=False)
    # ### end Alembic commands ###
