"""add product and store FKs to notification

Revision ID: be697d8d4cfa
Revises: ebcc9b1872b5
Create Date: 2026-07-15 11:47:23.898467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be697d8d4cfa'
down_revision: Union[str, Sequence[str], None] = 'ebcc9b1872b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'notification', 'store', ['store_id'], ['id'])
    op.create_foreign_key(None, 'notification', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.drop_constraint(None, 'notification', type_='foreignkey')
    # ### end Alembic commands ###
