"""added store table

Revision ID: c08ac8abdea7
Revises: 871793f81498
Create Date: 2026-03-15 18:42:36.481474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c08ac8abdea7'
down_revision: Union[str, Sequence[str], None] = '871793f81498'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('identifier', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('pics', sa.String(), nullable=True),
    sa.Column('delivered', sa.Boolean(), nullable=True),
    sa.Column('seen', sa.Boolean(), nullable=True),
    sa.Column('sender_deleted', sa.Boolean(), nullable=True),
    sa.Column('receiver_deleted', sa.Boolean(), nullable=True),
    sa.Column('time_of_chat', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_customer_id'), 'messages', ['customer_id'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index(op.f('ix_messages_identifier'), 'messages', ['identifier'], unique=False)
    op.create_index(op.f('ix_messages_receiver_deleted'), 'messages', ['receiver_deleted'], unique=False)
    op.create_index(op.f('ix_messages_sender_deleted'), 'messages', ['sender_deleted'], unique=False)
    op.create_index(op.f('ix_messages_user_id'), 'messages', ['user_id'], unique=False)
    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('store_photo', sa.String(), nullable=False),
    sa.Column('store_name', sa.String(), nullable=False),
    sa.Column('business_type', sa.String(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('founded', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_name')
    )
    op.create_index(op.f('ix_stores_category_id'), 'stores', ['category_id'], unique=False)
    op.create_index(op.f('ix_stores_id'), 'stores', ['id'], unique=False)
    op.create_index(op.f('ix_stores_owner_id'), 'stores', ['owner_id'], unique=False)
    op.create_index(op.f('ix_cartitems_cart_id'), 'cartitems', ['cart_id'], unique=False)
    op.create_index(op.f('ix_cartitems_product_id'), 'cartitems', ['product_id'], unique=False)
    op.add_column('carts', sa.Column('member_id', sa.Integer(), nullable=True))
    op.add_column('carts', sa.Column('check_out', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_carts_check_out'), 'carts', ['check_out'], unique=False)
    op.create_index(op.f('ix_carts_created_at'), 'carts', ['created_at'], unique=False)
    op.create_index(op.f('ix_carts_user_id'), 'carts', ['user_id'], unique=False)
    op.drop_constraint(op.f('carts_member_fkey'), 'carts', type_='foreignkey')
    op.create_foreign_key(None, 'carts', 'memberships', ['member_id'], ['id'], ondelete='CASCADE')
    op.drop_column('carts', 'member')
    op.add_column('memberships', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('memberships', sa.Column('is_pause', sa.Boolean(), nullable=True))
    op.add_column('memberships', sa.Column('delete_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_memberships_is_active'), 'memberships', ['is_active'], unique=False)
    op.create_index(op.f('ix_memberships_is_deleted'), 'memberships', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_memberships_is_pause'), 'memberships', ['is_pause'], unique=False)
    op.create_index(op.f('ix_memberships_membership_type'), 'memberships', ['membership_type'], unique=False)
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=True)
    op.drop_column('memberships', 'period_of_membership')
    op.drop_column('memberships', 'favourite_product_services')
    op.drop_column('memberships', 'offers')
    op.add_column('orderitems', sa.Column('cart_items', sa.Integer(), nullable=True))
    op.alter_column('orderitems', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.create_index(op.f('ix_orderitems_cart_items'), 'orderitems', ['cart_items'], unique=False)
    op.create_index(op.f('ix_orderitems_order_id'), 'orderitems', ['order_id'], unique=False)
    op.drop_constraint(op.f('orderitems_user_id_fkey'), 'orderitems', type_='foreignkey')
    op.drop_constraint(op.f('orderitems_product_id_fkey'), 'orderitems', type_='foreignkey')
    op.create_foreign_key(None, 'orderitems', 'cartitems', ['cart_items'], ['id'], ondelete='CASCADE')
    op.drop_column('orderitems', 'product_id')
    op.drop_column('orderitems', 'user_id')
    op.add_column('orders', sa.Column('order_delete', sa.Boolean(), nullable=True))
    op.alter_column('orders', 'total_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_member'), 'orders', ['member'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_index(op.f('ix_payments_payment_status'), 'payments', ['payment_status'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.add_column('products', sa.Column('primary_image', sa.String(), nullable=False))
    op.add_column('products', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.alter_column('products', 'product_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.add_column('replies', sa.Column('edited', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_replies_review_id'), 'replies', ['review_id'], unique=False)
    op.create_index(op.f('ix_replies_user_id'), 'replies', ['user_id'], unique=False)
    op.add_column('reviews', sa.Column('store_id', sa.Integer(), nullable=True))
    op.add_column('reviews', sa.Column('reply_count', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_reviews_date_of_review'), 'reviews', ['date_of_review'], unique=False)
    op.create_index(op.f('ix_reviews_product_id'), 'reviews', ['product_id'], unique=False)
    op.create_index(op.f('ix_reviews_store_id'), 'reviews', ['store_id'], unique=False)
    op.create_index(op.f('ix_reviews_user_id'), 'reviews', ['user_id'], unique=False)
    op.create_unique_constraint('user_store_review', 'reviews', ['user_id', 'store_id'])
    op.drop_constraint(op.f('reviews_product_id_fkey'), 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'reviews', 'stores', ['store_id'], ['id'])
    op.drop_column('reviews', 'product_name')
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.add_column('reviews', sa.Column('product_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('reviews_product_id_fkey'), 'reviews', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_store_review', 'reviews', type_='unique')
    op.drop_index(op.f('ix_reviews_user_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_store_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_product_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_date_of_review'), table_name='reviews')
    op.drop_column('reviews', 'reply_count')
    op.drop_column('reviews', 'store_id')
    op.drop_index(op.f('ix_replies_user_id'), table_name='replies')
    op.drop_index(op.f('ix_replies_review_id'), table_name='replies')
    op.drop_column('replies', 'edited')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.alter_column('products', 'product_price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_column('products', 'is_deleted')
    op.drop_column('products', 'primary_image')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_member'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.alter_column('orders', 'total_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_column('orders', 'order_delete')
    op.add_column('orderitems', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orderitems', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orderitems', type_='foreignkey')
    op.create_foreign_key(op.f('orderitems_product_id_fkey'), 'orderitems', 'products', ['product_id'], ['id'])
    op.create_foreign_key(op.f('orderitems_user_id_fkey'), 'orderitems', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_orderitems_order_id'), table_name='orderitems')
    op.drop_index(op.f('ix_orderitems_cart_items'), table_name='orderitems')
    op.alter_column('orderitems', 'price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_column('orderitems', 'cart_items')
    op.add_column('memberships', sa.Column('offers', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('memberships', sa.Column('favourite_product_services', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('memberships', sa.Column('period_of_membership', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_membership_type'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_is_pause'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_is_deleted'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_is_active'), table_name='memberships')
    op.drop_column('memberships', 'delete_date')
    op.drop_column('memberships', 'is_pause')
    op.drop_column('memberships', 'is_deleted')
    op.add_column('carts', sa.Column('member', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'carts', type_='foreignkey')
    op.create_foreign_key(op.f('carts_member_fkey'), 'carts', 'memberships', ['member'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_carts_user_id'), table_name='carts')
    op.drop_index(op.f('ix_carts_created_at'), table_name='carts')
    op.drop_index(op.f('ix_carts_check_out'), table_name='carts')
    op.drop_column('carts', 'check_out')
    op.drop_column('carts', 'member_id')
    op.drop_index(op.f('ix_cartitems_product_id'), table_name='cartitems')
    op.drop_index(op.f('ix_cartitems_cart_id'), table_name='cartitems')
    op.drop_index(op.f('ix_stores_owner_id'), table_name='stores')
    op.drop_index(op.f('ix_stores_id'), table_name='stores')
    op.drop_index(op.f('ix_stores_category_id'), table_name='stores')
    op.drop_table('stores')
    op.drop_index(op.f('ix_messages_user_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_sender_deleted'), table_name='messages')
    op.drop_index(op.f('ix_messages_receiver_deleted'), table_name='messages')
    op.drop_index(op.f('ix_messages_identifier'), table_name='messages')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_customer_id'), table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
