"""add partial and composite index

Revision ID: c2a20d56654c
Revises: 0d47ce9bb3c1
Create Date: 2026-08-17 12:17:51.267538

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "c2a20d56654c"
down_revision: Union[str, Sequence[str], None] = "0d47ce9bb3c1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("product", sa.Column("deleted_by", sa.Integer(), nullable=True))
    op.add_column(
        "product",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "product",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.drop_index(op.f("ix_product_category_id"), table_name="product")
    op.drop_index(op.f("ix_product_product_name"), table_name="product")
    op.drop_index(op.f("ix_product_store_id"), table_name="product")
    op.drop_index(op.f("ix_product_sub_category_id"), table_name="product")
    op.create_index(
        "idx_product_category_active",
        "product",
        ["category_id", "sub_category_id"],
        unique=False,
        postgresql_where=sa.text("is_deleted IS False"),
    )
    op.create_index(
        "idx_product_store_active",
        "product",
        ["store_id"],
        unique=False,
        postgresql_where=sa.text("is_deleted IS False"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_product_store_active",
        table_name="product",
        postgresql_where=sa.text("is_deleted IS False"),
    )
    op.drop_index(
        "idx_product_category_active",
        table_name="product",
        postgresql_where=sa.text("is_deleted IS False"),
    )
    op.create_index(
        op.f("ix_product_sub_category_id"), "product", ["sub_category_id"], unique=False
    )
    op.create_index(op.f("ix_product_store_id"), "product", ["store_id"], unique=False)
    op.create_index(
        op.f("ix_product_product_name"), "product", ["product_name"], unique=False
    )
    op.create_index(
        op.f("ix_product_category_id"), "product", ["category_id"], unique=False
    )
    op.drop_column("product", "updated_at")
    op.drop_column("product", "created_at")
    op.drop_column("product", "deleted_by")
    # ### end Alembic commands ###
