"""add is_read column to notifications table

Revision ID: c46bec1d5a69
Revises: 7917abc87191
Create Date: 2026-05-23 21:25:22.589371

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "c46bec1d5a69"
down_revision: Union[str, Sequence[str], None] = "7917abc87191"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("notifications", "is_read")
    # ### end Alembic commands ###
