"""add nullable = True for delivery address column in order table

Revision ID: c594b52ef3ba
Revises: f4445dc5670f
Create Date: 2026-05-28 20:06:28.599886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c594b52ef3ba'
down_revision: Union[str, Sequence[str], None] = 'f4445dc5670f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'delivery_address_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'delivery_address_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
