"""add previous_rejected_reason column to StoreAccount table

Revision ID: c9add857554c
Revises: 31eea10f4332
Create Date: 2026-05-26 16:03:24.979990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9add857554c'
down_revision: Union[str, Sequence[str], None] = '31eea10f4332'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_account', sa.Column('previous_rejected_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_account', 'previous_rejected_reason')
    # ### end Alembic commands ###
