"""link message table to ticket table

Revision ID: c9fcb3d0fb21
Revises: 312cdbe11b38
Create Date: 2026-04-22 19:26:27.813760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9fcb3d0fb21'
down_revision: Union[str, Sequence[str], None] = '312cdbe11b38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('ticket_id', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('support_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_messages_identifier'), table_name='messages')
    op.create_index(op.f('ix_messages_support_id'), 'messages', ['support_id'], unique=False)
    op.create_index(op.f('ix_messages_ticket_id'), 'messages', ['ticket_id'], unique=False)
    op.create_foreign_key(None, 'messages', 'tickets', ['ticket_id'], ['id'])
    op.drop_column('messages', 'identifier')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('identifier', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_messages_ticket_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_support_id'), table_name='messages')
    op.create_index(op.f('ix_messages_identifier'), 'messages', ['identifier'], unique=False)
    op.drop_column('messages', 'support_id')
    op.drop_column('messages', 'ticket_id')
    # ### end Alembic commands ###
