"""refactor: migrate stores to multi-owner and multi-staff architecture

Revision ID: ce64a73435a4
Revises: 01ef0d7b0fe8
Create Date: 2026-03-16 16:58:07.399371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce64a73435a4'
down_revision: Union[str, Sequence[str], None] = '01ef0d7b0fe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_owners',
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('stores_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stores_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('users_id', 'stores_id')
    )
    op.create_index(op.f('ix_store_owners_stores_id'), 'store_owners', ['stores_id'], unique=False)
    op.create_index(op.f('ix_store_owners_users_id'), 'store_owners', ['users_id'], unique=False)
    op.create_table('store_staffs',
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('stores_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stores_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('users_id', 'stores_id')
    )
    op.create_index(op.f('ix_store_staffs_stores_id'), 'store_staffs', ['stores_id'], unique=False)
    op.create_index(op.f('ix_store_staffs_users_id'), 'store_staffs', ['users_id'], unique=False)
    op.drop_index(op.f('ix_stores_owner_id'), table_name='stores')
    op.drop_constraint(op.f('stores_owner_id_fkey'), 'stores', type_='foreignkey')
    op.drop_column('stores', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('stores_owner_id_fkey'), 'stores', 'users', ['owner_id'], ['id'])
    op.create_index(op.f('ix_stores_owner_id'), 'stores', ['owner_id'], unique=False)
    op.drop_index(op.f('ix_store_staffs_users_id'), table_name='store_staffs')
    op.drop_index(op.f('ix_store_staffs_stores_id'), table_name='store_staffs')
    op.drop_table('store_staffs')
    op.drop_index(op.f('ix_store_owners_users_id'), table_name='store_owners')
    op.drop_index(op.f('ix_store_owners_stores_id'), table_name='store_owners')
    op.drop_table('store_owners')
    # ### end Alembic commands ###
