"""change category column name to category_name

Revision ID: d8937728c84a
Revises: da217c931aad
Create Date: 2026-05-06 14:17:03.956313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8937728c84a'
down_revision: Union[str, Sequence[str], None] = 'da217c931aad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('category_name', sa.String(), nullable=False))
    op.create_index(op.f('ix_stores_category_name'), 'stores', ['category_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stores_category_name'), table_name='stores')
    op.drop_column('stores', 'category_name')
    # ### end Alembic commands ###
