"""add check constraint to user table

Revision ID: da01c8a90dcd
Revises: 039add157915
Create Date: 2026-08-01 12:23:35.077256

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "da01c8a90dcd"
down_revision: Union[str, Sequence[str], None] = "039add157915"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("idx_is_banned"), table_name="user")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("idx_is_banned"), "user", ["is_banned"], unique=False)
    op.alter_column(
        "user",
        "ban_period",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    # ### end Alembic commands ###
