"""change sub_category column type hint to list

Revision ID: da217c931aad
Revises: 7dd5ec9428e4
Create Date: 2026-05-06 14:04:31.374028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da217c931aad'
down_revision: Union[str, Sequence[str], None] = '7dd5ec9428e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('sub_category', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_index(op.f('ix_stores_sub_category_id'), table_name='stores')
    op.create_index(op.f('ix_stores_sub_category'), 'stores', ['sub_category'], unique=False)
    op.drop_constraint(op.f('stores_sub_category_id_fkey'), 'stores', type_='foreignkey')
    op.drop_column('stores', 'sub_category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('sub_category_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('stores_sub_category_id_fkey'), 'stores', 'subcategories', ['sub_category_id'], ['id'])
    op.drop_index(op.f('ix_stores_sub_category'), table_name='stores')
    op.create_index(op.f('ix_stores_sub_category_id'), 'stores', ['sub_category_id'], unique=False)
    op.drop_column('stores', 'sub_category')
    # ### end Alembic commands ###
