"""add refund_reason column to refund table

Revision ID: dd70dff349bd
Revises: 1a3677ce04d8
Create Date: 2026-06-08 17:12:43.608365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd70dff349bd'
down_revision: Union[str, Sequence[str], None] = '1a3677ce04d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('refund', sa.Column('refund_reason', sa.String(), nullable=False))
    op.add_column('refund', sa.Column('last_event_at', sa.DateTime(timezone=True), nullable=False))
    op.create_index(op.f('ix_refund_last_event_at'), 'refund', ['last_event_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refund_last_event_at'), table_name='refund')
    op.drop_column('refund', 'last_event_at')
    op.drop_column('refund', 'refund_reason')
    op.drop_column('payment', 'last_updated')
    # ### end Alembic commands ###
