"""add tax amount and shipping fee columns to store table

Revision ID: e0cdc0ce3851
Revises: 42d7b925d1dc
Create Date: 2026-04-15 19:21:03.751038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0cdc0ce3851'
down_revision: Union[str, Sequence[str], None] = '42d7b925d1dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('shipping_fee', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('stores', sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'tax_amount')
    op.drop_column('stores', 'shipping_fee')
    # ### end Alembic commands ###
