"""normalize ProductImage table

Revision ID: e0d927ca6b37
Revises: 7077e7b3ab5d
Create Date: 2026-05-20 12:55:44.675516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0d927ca6b37'
down_revision: Union[str, Sequence[str], None] = '7077e7b3ab5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_images', sa.Column('image', sa.String(), nullable=False))
    op.drop_column('product_images', 'image_3')
    op.drop_column('product_images', 'image_2')
    op.drop_column('product_images', 'image_4')
    op.drop_column('product_images', 'image_5')
    op.drop_column('product_images', 'image_1')
    op.alter_column('products', 'product_description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'product_description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.add_column('product_images', sa.Column('image_1', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('product_images', sa.Column('image_5', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('product_images', sa.Column('image_4', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('product_images', sa.Column('image_2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('product_images', sa.Column('image_3', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('product_images', 'image')
    # ### end Alembic commands ###
