"""add type column to notification table

Revision ID: e66ccf297b11
Revises: fdf1d48d57f4
Create Date: 2026-06-19 17:10:24.950223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e66ccf297b11'
down_revision: Union[str, Sequence[str], None] = 'fdf1d48d57f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('status', sa.String(), nullable=True))
    op.add_column('notification', sa.Column('type', sa.String(), nullable=True))
    op.drop_column('notification', 'payment_status')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    op.add_column('notification', sa.Column('payment_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('notification', 'type')
    op.drop_column('notification', 'status')
    # ### end Alembic commands ###
