"""add last_event_at column to subscription table

Revision ID: e69fbcbdec78
Revises: 5e2934133d66
Create Date: 2026-04-17 19:14:19.086161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e69fbcbdec78'
down_revision: Union[str, Sequence[str], None] = '5e2934133d66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('last_event_at', sa.DateTime(timezone=True), nullable=False))
    op.create_index(op.f('ix_subscriptions_last_event_at'), 'subscriptions', ['last_event_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_last_event_at'), table_name='subscriptions')
    op.drop_column('subscriptions', 'last_event_at')
    # ### end Alembic commands ###
