"""add motto to store table

Revision ID: e8054daf51b9
Revises: 324c275e1546
Create Date: 2026-03-24 16:38:05.597742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8054daf51b9'
down_revision: Union[str, Sequence[str], None] = '324c275e1546'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('motto', sa.String(), nullable=False))
    op.add_column('stores', sa.Column('edited_name', sa.Boolean(), nullable=False))
    op.add_column('stores', sa.Column('store_previous_name', sa.String(), nullable=False))
    op.create_index(op.f('ix_stores_store_previous_name'), 'stores', ['store_previous_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stores_store_previous_name'), table_name='stores')
    op.drop_column('stores', 'store_previous_name')
    op.drop_column('stores', 'edited_name')
    op.drop_column('stores', 'motto')
    # ### end Alembic commands ###
