"""add store account table

Revision ID: ee0c6724434e
Revises: e8054daf51b9
Create Date: 2026-03-25 16:23:15.672622

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ee0c6724434e"
down_revision: Union[str, Sequence[str], None] = "e8054daf51b9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "store_accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("store_id", sa.Integer(), nullable=False),
        sa.Column("account_name", sa.String(), nullable=False),
        sa.Column("account_number", sa.String(), nullable=False),
        sa.Column("tax_identification_number", sa.String(), nullable=False),
        sa.Column("identification_number", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_store_accounts_id"), "store_accounts", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_store_accounts_store_id"), "store_accounts", ["store_id"], unique=False
    )
    op.add_column("orders", sa.Column("store_id", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_orders_store_id"), "orders", ["store_id"], unique=False)
    op.create_foreign_key(None, "orders", "stores", ["store_id"], ["id"])
    op.alter_column("payments", "user_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("payments", "order_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "payments", "payment_method", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "payments",
        "amount_paid",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=10, scale=2),
        nullable=False,
    )
    op.alter_column(
        "payments", "payment_status", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "payments",
        "shipping_fee",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=10, scale=2),
        nullable=False,
    )
    op.alter_column(
        "payments",
        "discount",
        existing_type=sa.INTEGER(),
        type_=sa.Numeric(precision=10, scale=2),
        nullable=False,
    )
    op.alter_column(
        "payments",
        "tax",
        existing_type=sa.INTEGER(),
        type_=sa.Numeric(precision=10, scale=2),
        nullable=False,
    )
    op.alter_column(
        "payments", "transaction_id", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "payments",
        "payment_date",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.create_index(
        op.f("ix_payments_transaction_id"), "payments", ["transaction_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_payments_transaction_id"), table_name="payments")
    op.alter_column(
        "payments",
        "payment_date",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "payments", "transaction_id", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "payments",
        "tax",
        existing_type=sa.Numeric(precision=10, scale=2),
        type_=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "payments",
        "discount",
        existing_type=sa.Numeric(precision=10, scale=2),
        type_=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "payments",
        "shipping_fee",
        existing_type=sa.Numeric(precision=10, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        "payments", "payment_status", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "payments",
        "amount_paid",
        existing_type=sa.Numeric(precision=10, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        "payments", "payment_method", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column("payments", "order_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("payments", "user_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_constraint(None, "orders", type_="foreignkey")
    op.drop_index(op.f("ix_orders_store_id"), table_name="orders")
    op.drop_column("orders", "store_id")
    op.drop_index(op.f("ix_store_accounts_store_id"), table_name="store_accounts")
    op.drop_index(op.f("ix_store_accounts_id"), table_name="store_accounts")
    op.drop_table("store_accounts")
    # ### end Alembic commands ###
