"""add native enums for order status

Revision ID: ef519e58fc68
Revises: f6a2c406a9ab
Create Date: 2026-04-04 18:18:00.946758

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ef519e58fc68"
down_revision: Union[str, Sequence[str], None] = "f6a2c406a9ab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.dialects import postgresql

    order_status_enum = postgresql.ENUM(
        "pending", "processing", "shipped", "delivered", "cancelled", name="orderstatus"
    )
    order_status_enum.create(op.get_bind())
    op.alter_column(
        "orders",
        "status",
        existing_type=sa.VARCHAR(),
        type_=sa.Enum(
            "pending",
            "processing",
            "shipped",
            "delivered",
            "cancelled",
            name="orderstatus",
        ),
        existing_nullable=True,
        postgresql_using="status::orderstatus",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "orders",
        "status",
        existing_type=sa.Enum(
            "pending",
            "processing",
            "shipped",
            "delivered",
            "cancelled",
            name="orderstatus",
        ),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
