"""link store to peoduct

Revision ID: f6229a9292f3
Revises: 42a262fb2250
Create Date: 2026-03-31 16:26:39.311203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6229a9292f3'
down_revision: Union[str, Sequence[str], None] = '42a262fb2250'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('store_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_products_store_id'), 'products', ['store_id'], unique=False)
    op.create_foreign_key(None, 'products', 'stores', ['store_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_store_id'), table_name='products')
    op.drop_column('products', 'store_id')
    # ### end Alembic commands ###
