"""link store to cart

Revision ID: f6a2c406a9ab
Revises: 904c47f037d2
Create Date: 2026-04-04 13:03:06.513893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6a2c406a9ab'
down_revision: Union[str, Sequence[str], None] = '904c47f037d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('store_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_carts_store_id'), 'carts', ['store_id'], unique=False)
    op.create_foreign_key(None, 'carts', 'stores', ['store_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'carts', type_='foreignkey')
    op.drop_index(op.f('ix_carts_store_id'), table_name='carts')
    op.drop_column('carts', 'store_id')
    # ### end Alembic commands ###
