"""add nullable = True for reference id column in order table

Revision ID: f7a839c785c3
Revises: e758774bc891
Create Date: 2026-05-28 20:16:48.769552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7a839c785c3'
down_revision: Union[str, Sequence[str], None] = 'e758774bc891'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'reference_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'reference_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
