"""add is_deleted column

Revision ID: f941f8f3810c
Revises: 720b25063727
Create Date: 2026-04-27 15:50:46.198738

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f941f8f3810c"
down_revision: Union[str, Sequence[str], None] = "720b25063727"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_categories_is_deleted"), "categories", ["is_deleted"], unique=False
    )
    op.add_column(
        "subcategories", sa.Column("is_deleted", sa.Boolean(), nullable=False)
    )
    op.create_index(
        op.f("ix_subcategories_is_deleted"),
        "subcategories",
        ["is_deleted"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_subcategories_is_deleted"), table_name="subcategories")
    op.drop_column("subcategories", "is_deleted")
    op.drop_index(op.f("ix_categories_is_deleted"), table_name="categories")
    op.drop_column("categories", "is_deleted")
    # ### end Alembic commands ###
