"""remove business_type

Revision ID: f9aa720f7021
Revises: f941f8f3810c
Create Date: 2026-04-27 18:53:01.342835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f9aa720f7021'
down_revision: Union[str, Sequence[str], None] = 'f941f8f3810c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stores', 'business_type',
               existing_type=postgresql.ENUM('beauty_and_hair', 'skincare', 'hair', 'electronics', 'fashion', 'kitchen_wares', 'groceries', 'fruits_and_vegetables', 'footwear', 'bags', 'luggages', 'games', 'computers', name='businesstype'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stores', 'business_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('beauty_and_hair', 'skincare', 'hair', 'electronics', 'fashion', 'kitchen_wares', 'groceries', 'fruits_and_vegetables', 'footwear', 'bags', 'luggages', 'games', 'computers', name='businesstype'),
               existing_nullable=False)
    # ### end Alembic commands ###
