"""add discount amount column to payment table

Revision ID: fb642ea1fc89
Revises: 41d131baa011
Create Date: 2026-04-08 17:34:02.855655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb642ea1fc89'
down_revision: Union[str, Sequence[str], None] = '41d131baa011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'discount_amount')
    # ### end Alembic commands ###
