"""ensure nullability for last event id column in subscription table

Revision ID: fdf1d48d57f4
Revises: a2554765a2ff
Create Date: 2026-06-10 14:33:44.141506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fdf1d48d57f4'
down_revision: Union[str, Sequence[str], None] = 'a2554765a2ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscription', 'customer_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('subscription', 'reference_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('subscription', 'last_event_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('subscription', 'last_event_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('subscription', 'expire_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscription', 'expire_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('subscription', 'last_event_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('subscription', 'last_event_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('subscription', 'reference_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('subscription', 'customer_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
